packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': set this to true or false
  '@swc/core': true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - msw
  - sharp
  - unrs-resolver
