/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoDefaultAddressDTO {
  address_line1?: string;
  address_line2?: string;
  city?: string;
  country?: string;
  id?: number;
  phone?: string;
  postal_code?: string;
  state?: string;
}

export interface DtoOrderResponse {
  created_at?: string;
  id?: number;
  order_number?: string;
  status?: string;
  total_amount?: number;
}

export interface DtoDashboardSummaryResponse {
  address_count?: number;
  created_at?: string;
  default_billing_address?: DtoDefaultAddressDTO;
  default_shipping_address?: DtoDefaultAddressDTO;
  email?: string;
  email_verified_at?: string;
  first_name?: string;
  id?: number;
  is_active?: boolean;
  last_name?: string;
  liked_products_count?: number;
  phone?: string;
  recent_orders?: DtoOrderResponse[];
  role?: string;
}

export type GetAccountSummary200 = UtilsResponse & {
  data?: DtoDashboardSummaryResponse;
};

