/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoPushSubscriptionKeys {
  auth: string;
  p256dh: string;
}

export interface DtoRegisterPushSubscriptionRequest {
  endpoint: string;
  keys: DtoPushSubscriptionKeys;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

