/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export type ModelsAddressAddressType = typeof ModelsAddressAddressType[keyof typeof ModelsAddressAddressType];


export const ModelsAddressAddressType = {
  shipping: 'shipping',
  billing: 'billing',
  both: 'both',
} as const;

export interface GormDeletedAt {
  time?: string;
  /** Valid is true if Time is not NULL */
  valid?: boolean;
}

export interface ModelsAddress {
  address_line1: string;
  address_line2?: string;
  address_type?: ModelsAddressAddressType;
  city: string;
  country: string;
  created_at?: string;
  deleted_at?: GormDeletedAt;
  id?: number;
  instructions?: string;
  is_default?: boolean;
  phone: string;
  postal_code: string;
  recipient_name: string;
  state?: string;
  updated_at?: string;
  user_id?: number;
}

export type GetAddresses200Data = {
  addresses?: ModelsAddress[];
};

export type GetAddresses200 = UtilsResponse & {
  data?: GetAddresses200Data;
};

