/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type { DtoEmptyResponse, UtilsResponse } from './-addresses-{id}-default-patch.schemas';

import { customInstance } from '../lib/api/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Marks a specific address as the default (for its address_type, e.g., shipping or billing). Only one default per type.
 * @summary Set default address
 */
export const patchAddressesIdDefault = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<DtoEmptyResponse>(
    { url: `/addresses/${id}/default`, method: 'PATCH', signal },
    options
  );
};

export const getPatchAddressesIdDefaultMutationOptions = <
  TError = UtilsResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchAddressesIdDefault>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchAddressesIdDefault>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['patchAddressesIdDefault'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchAddressesIdDefault>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return patchAddressesIdDefault(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchAddressesIdDefaultMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAddressesIdDefault>>
>;

export type PatchAddressesIdDefaultMutationError = UtilsResponse;

/**
 * @summary Set default address
 */
export const usePatchAddressesIdDefault = <TError = UtilsResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchAddressesIdDefault>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patchAddressesIdDefault>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getPatchAddressesIdDefaultMutationOptions(options), queryClient);
};
