/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoAddressSingleResponse,
  GetAddressesDefaultParams,
  UtilsResponse
} from './-addresses-default-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the default shipping or billing address for the current user.
 * @summary Get default address
 */
export const getAddressesDefault = (
    params?: GetAddressesDefaultParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DtoAddressSingleResponse>(
      {url: `/addresses/default`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetAddressesDefaultQueryKey = (params?: GetAddressesDefaultParams,) => {
    return [
    `/addresses/default`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAddressesDefaultQueryOptions = <TData = Awaited<ReturnType<typeof getAddressesDefault>>, TError = UtilsResponse>(params?: GetAddressesDefaultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAddressesDefault>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAddressesDefaultQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAddressesDefault>>> = ({ signal }) => getAddressesDefault(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAddressesDefault>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAddressesDefaultQueryResult = NonNullable<Awaited<ReturnType<typeof getAddressesDefault>>>
export type GetAddressesDefaultQueryError = UtilsResponse


export function useGetAddressesDefault<TData = Awaited<ReturnType<typeof getAddressesDefault>>, TError = UtilsResponse>(
 params: undefined |  GetAddressesDefaultParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAddressesDefault>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAddressesDefault>>,
          TError,
          Awaited<ReturnType<typeof getAddressesDefault>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAddressesDefault<TData = Awaited<ReturnType<typeof getAddressesDefault>>, TError = UtilsResponse>(
 params?: GetAddressesDefaultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAddressesDefault>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAddressesDefault>>,
          TError,
          Awaited<ReturnType<typeof getAddressesDefault>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAddressesDefault<TData = Awaited<ReturnType<typeof getAddressesDefault>>, TError = UtilsResponse>(
 params?: GetAddressesDefaultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAddressesDefault>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get default address
 */

export function useGetAddressesDefault<TData = Awaited<ReturnType<typeof getAddressesDefault>>, TError = UtilsResponse>(
 params?: GetAddressesDefaultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAddressesDefault>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAddressesDefaultQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







