/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export type DtoUpdateAddressRequestAddressType =
  (typeof DtoUpdateAddressRequestAddressType)[keyof typeof DtoUpdateAddressRequestAddressType];

export const DtoUpdateAddressRequestAddressType = {
  shipping: 'shipping',
  billing: 'billing',
  both: 'both'
} as const;

export interface DtoUpdateAddressRequest {
  address_line1: string;
  address_line2?: string;
  address_type?: DtoUpdateAddressRequestAddressType;
  city: string;
  country: string;
  instructions?: string;
  is_default?: boolean;
  phone?: string;
  postal_code: string;
  recipient_name: string;
  state?: string;
}

export type ModelsAddressAddressType =
  (typeof ModelsAddressAddressType)[keyof typeof ModelsAddressAddressType];

export const ModelsAddressAddressType = {
  shipping: 'shipping',
  billing: 'billing',
  both: 'both'
} as const;

export interface GormDeletedAt {
  time?: string;
  /** Valid is true if Time is not NULL */
  valid?: boolean;
}

export interface ModelsAddress {
  address_line1: string;
  address_line2?: string;
  address_type?: ModelsAddressAddressType;
  city: string;
  country: string;
  created_at?: string;
  deleted_at?: GormDeletedAt;
  id?: number;
  instructions?: string;
  is_default?: boolean;
  phone: string;
  postal_code: string;
  recipient_name: string;
  state?: string;
  updated_at?: string;
  user_id?: number;
}

export interface DtoAddressSingleResponse {
  address?: ModelsAddress;
  code?: number;
  message?: string;
  success?: boolean;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}
