/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UtilsResponse
} from './-admin-workflows-{id}-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Delete workflow (admin)
 */
export const deleteAdminWorkflowsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/admin/workflows/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteAdminWorkflowsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminWorkflowsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminWorkflowsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteAdminWorkflowsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminWorkflowsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminWorkflowsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminWorkflowsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminWorkflowsId>>>

    export type DeleteAdminWorkflowsIdMutationError = unknown

    /**
 * @summary Delete workflow (admin)
 */
export const useDeleteAdminWorkflowsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminWorkflowsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminWorkflowsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteAdminWorkflowsIdMutationOptions(options), queryClient);
    }

