/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export type DtoUpdateUserRoleRequestRole = typeof DtoUpdateUserRoleRequestRole[keyof typeof DtoUpdateUserRoleRequestRole];


export const DtoUpdateUserRoleRequestRole = {
  admin: 'admin',
  user: 'user',
} as const;

export interface DtoUpdateUserRoleRequest {
  role: DtoUpdateUserRoleRequestRole;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

