/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoAdminUserResponse {
  created_at?: string;
  email?: string;
  email_verified_at?: string;
  first_name?: string;
  id?: number;
  is_active?: boolean;
  last_login_at?: string;
  last_name?: string;
  role?: string;
}

export type GetAdminUsersParams = {
/**
 * Items per page (default 20)
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
/**
 * Search name or email (partial)
 */
search?: string;
/**
 * Email search (partial)
 */
email?: string;
/**
 * Filter by role (admin|user)
 */
role?: string;
/**
 * Filter by active status
 */
is_active?: boolean;
};

export type GetAdminUsers200Data = {
  limit?: number;
  offset?: number;
  total?: number;
  users?: DtoAdminUserResponse[];
};

export type GetAdminUsers200 = UtilsResponse & {
  data?: GetAdminUsers200Data;
};

