/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoAdminRevenueDailyRow {
  avg_order_value?: number;
  date?: string;
  orders?: number;
  paid_orders?: number;
  revenue?: number;
}

export interface DtoAdminDashboardKPI {
  change_percent?: number;
  previous_value?: number;
  value?: number;
}

export interface DtoAdminRevenueReportSummary {
  avg_daily_revenue?: DtoAdminDashboardKPI;
  avg_order_value?: DtoAdminDashboardKPI;
  orders?: DtoAdminDashboardKPI;
  revenue?: DtoAdminDashboardKPI;
}

export interface DtoAdminRevenueReportResponse {
  daily?: DtoAdminRevenueDailyRow[];
  generated_at?: string;
  period?: string;
  summary?: DtoAdminRevenueReportSummary;
}

export type GetAdminReportsRevenueParams = {
/**
 * Period: 7d, 30d, or 90d (default 30d)
 */
period?: string;
};

export type GetAdminReportsRevenue200 = UtilsResponse & {
  data?: DtoAdminRevenueReportResponse;
};

