/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoUpdateWorkflowRequest,
  UtilsResponse
} from './-admin-workflows-{id}-patch.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Update workflow (admin)
 */
export const patchAdminWorkflowsId = (
    id: number,
    dtoUpdateWorkflowRequest: DtoUpdateWorkflowRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/admin/workflows/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: dtoUpdateWorkflowRequest, signal
    },
      options);
    }



export const getPatchAdminWorkflowsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminWorkflowsId>>, TError,{id: number;data: DtoUpdateWorkflowRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminWorkflowsId>>, TError,{id: number;data: DtoUpdateWorkflowRequest}, TContext> => {

const mutationKey = ['patchAdminWorkflowsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminWorkflowsId>>, {id: number;data: DtoUpdateWorkflowRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminWorkflowsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminWorkflowsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminWorkflowsId>>>
    export type PatchAdminWorkflowsIdMutationBody = DtoUpdateWorkflowRequest
    export type PatchAdminWorkflowsIdMutationError = unknown

    /**
 * @summary Update workflow (admin)
 */
export const usePatchAdminWorkflowsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminWorkflowsId>>, TError,{id: number;data: DtoUpdateWorkflowRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminWorkflowsId>>,
        TError,
        {id: number;data: DtoUpdateWorkflowRequest},
        TContext
      > => {
      return useMutation(getPatchAdminWorkflowsIdMutationOptions(options), queryClient);
    }

