/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCreateWorkflowRequest,
  UtilsResponse
} from './-admin-workflows-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create workflow (admin)
 */
export const postAdminWorkflows = (
    dtoCreateWorkflowRequest: DtoCreateWorkflowRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/admin/workflows`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoCreateWorkflowRequest, signal
    },
      options);
    }



export const getPostAdminWorkflowsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminWorkflows>>, TError,{data: DtoCreateWorkflowRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminWorkflows>>, TError,{data: DtoCreateWorkflowRequest}, TContext> => {

const mutationKey = ['postAdminWorkflows'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminWorkflows>>, {data: DtoCreateWorkflowRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAdminWorkflows(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminWorkflowsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminWorkflows>>>
    export type PostAdminWorkflowsMutationBody = DtoCreateWorkflowRequest
    export type PostAdminWorkflowsMutationError = unknown

    /**
 * @summary Create workflow (admin)
 */
export const usePostAdminWorkflows = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminWorkflows>>, TError,{data: DtoCreateWorkflowRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminWorkflows>>,
        TError,
        {data: DtoCreateWorkflowRequest},
        TContext
      > => {
      return useMutation(getPostAdminWorkflowsMutationOptions(options), queryClient);
    }

