/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export type GetAdminOrdersExportParams = {
/**
 * Filter by status
 */
status?: string;
/**
 * Start date (YYYY-MM-DD)
 */
from_date?: string;
/**
 * End date (YYYY-MM-DD)
 */
to_date?: string;
};

