/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DeleteAdminCategoriesBulkBody,
  DtoEmptyResponse,
  UtilsResponse
} from './-admin-categories-bulk-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Deletes multiple categories by their IDs. Only accessible by users with the "admin" role.
 * Cannot delete categories that have child categories – delete children first.
 * @summary Bulk delete categories
 */
export const deleteAdminCategoriesBulk = (
    deleteAdminCategoriesBulkBody: DeleteAdminCategoriesBulkBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DtoEmptyResponse>(
      {url: `/admin/categories/bulk`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteAdminCategoriesBulkBody, signal
    },
      options);
    }



export const getDeleteAdminCategoriesBulkMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCategoriesBulk>>, TError,{data: DeleteAdminCategoriesBulkBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCategoriesBulk>>, TError,{data: DeleteAdminCategoriesBulkBody}, TContext> => {

const mutationKey = ['deleteAdminCategoriesBulk'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminCategoriesBulk>>, {data: DeleteAdminCategoriesBulkBody}> = (props) => {
          const {data} = props ?? {};

          return  deleteAdminCategoriesBulk(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminCategoriesBulkMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminCategoriesBulk>>>
    export type DeleteAdminCategoriesBulkMutationBody = DeleteAdminCategoriesBulkBody
    export type DeleteAdminCategoriesBulkMutationError = UtilsResponse

    /**
 * @summary Bulk delete categories
 */
export const useDeleteAdminCategoriesBulk = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCategoriesBulk>>, TError,{data: DeleteAdminCategoriesBulkBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminCategoriesBulk>>,
        TError,
        {data: DeleteAdminCategoriesBulkBody},
        TContext
      > => {
      return useMutation(getDeleteAdminCategoriesBulkMutationOptions(options), queryClient);
    }

