/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoUpdateMenuItemRequest {
  display_order?: number;
  group_id: number;
  href?: string;
  icon: string;
  label: string;
  parent_id?: number;
  permission?: string;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface ModelsMenuItem {
  children?: ModelsMenuItem[];
  created_at?: string;
  display_order?: number;
  group_id?: number;
  href?: string;
  icon?: string;
  id?: number;
  label?: string;
  parent_id?: number;
  permission?: string;
  updated_at?: string;
}

export type PutAdminMenuItemsId200 = UtilsResponse & {
  data?: ModelsMenuItem;
};

