/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoUpdateStoreRequest,
  PutAdminStoresId200,
  UtilsResponse
} from './-admin-stores-{id}-put.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Update store details (admin only)
 * @summary Update store
 */
export const putAdminStoresId = (
    id: number,
    dtoUpdateStoreRequest: DtoUpdateStoreRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PutAdminStoresId200>(
      {url: `/admin/stores/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dtoUpdateStoreRequest, signal
    },
      options);
    }



export const getPutAdminStoresIdMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminStoresId>>, TError,{id: number;data: DtoUpdateStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putAdminStoresId>>, TError,{id: number;data: DtoUpdateStoreRequest}, TContext> => {

const mutationKey = ['putAdminStoresId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAdminStoresId>>, {id: number;data: DtoUpdateStoreRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putAdminStoresId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutAdminStoresIdMutationResult = NonNullable<Awaited<ReturnType<typeof putAdminStoresId>>>
    export type PutAdminStoresIdMutationBody = DtoUpdateStoreRequest
    export type PutAdminStoresIdMutationError = UtilsResponse

    /**
 * @summary Update store
 */
export const usePutAdminStoresId = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminStoresId>>, TError,{id: number;data: DtoUpdateStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAdminStoresId>>,
        TError,
        {id: number;data: DtoUpdateStoreRequest},
        TContext
      > => {
      return useMutation(getPutAdminStoresIdMutationOptions(options), queryClient);
    }

