/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminInventoryProductsIdHistory200,
  GetAdminInventoryProductsIdHistoryParams,
  UtilsResponse
} from './-admin-inventory-products-{id}-history-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Paginated adjustment ledger for a single product
 * @summary Product inventory history
 */
export const getAdminInventoryProductsIdHistory = (
    id: number,
    params?: GetAdminInventoryProductsIdHistoryParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetAdminInventoryProductsIdHistory200>(
      {url: `/admin/inventory/products/${id}/history`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetAdminInventoryProductsIdHistoryQueryKey = (id: number,
    params?: GetAdminInventoryProductsIdHistoryParams,) => {
    return [
    `/admin/inventory/products/${id}/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminInventoryProductsIdHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError = UtilsResponse>(id: number,
    params?: GetAdminInventoryProductsIdHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminInventoryProductsIdHistoryQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>> = ({ signal }) => getAdminInventoryProductsIdHistory(id,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminInventoryProductsIdHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>>
export type GetAdminInventoryProductsIdHistoryQueryError = UtilsResponse


export function useGetAdminInventoryProductsIdHistory<TData = Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError = UtilsResponse>(
 id: number,
    params: undefined |  GetAdminInventoryProductsIdHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>,
          TError,
          Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminInventoryProductsIdHistory<TData = Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError = UtilsResponse>(
 id: number,
    params?: GetAdminInventoryProductsIdHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>,
          TError,
          Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminInventoryProductsIdHistory<TData = Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError = UtilsResponse>(
 id: number,
    params?: GetAdminInventoryProductsIdHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Product inventory history
 */

export function useGetAdminInventoryProductsIdHistory<TData = Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError = UtilsResponse>(
 id: number,
    params?: GetAdminInventoryProductsIdHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryProductsIdHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminInventoryProductsIdHistoryQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







