/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoToggleUserActiveRequest,
  UtilsResponse
} from './-admin-users-{id}-active-patch.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Enables or disables a user account.
 * @summary Toggle user active status (admin)
 */
export const patchAdminUsersIdActive = (
    id: number,
    dtoToggleUserActiveRequest: DtoToggleUserActiveRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/admin/users/${id}/active`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: dtoToggleUserActiveRequest, signal
    },
      options);
    }



export const getPatchAdminUsersIdActiveMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminUsersIdActive>>, TError,{id: number;data: DtoToggleUserActiveRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminUsersIdActive>>, TError,{id: number;data: DtoToggleUserActiveRequest}, TContext> => {

const mutationKey = ['patchAdminUsersIdActive'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminUsersIdActive>>, {id: number;data: DtoToggleUserActiveRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAdminUsersIdActive(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminUsersIdActiveMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminUsersIdActive>>>
    export type PatchAdminUsersIdActiveMutationBody = DtoToggleUserActiveRequest
    export type PatchAdminUsersIdActiveMutationError = UtilsResponse

    /**
 * @summary Toggle user active status (admin)
 */
export const usePatchAdminUsersIdActive = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminUsersIdActive>>, TError,{id: number;data: DtoToggleUserActiveRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminUsersIdActive>>,
        TError,
        {id: number;data: DtoToggleUserActiveRequest},
        TContext
      > => {
      return useMutation(getPatchAdminUsersIdActiveMutationOptions(options), queryClient);
    }

