/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PostAdminShipments201,
  PostAdminShipmentsBody,
  UtilsResponse
} from './-admin-shipments-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a shipment record and triggers a background job to process it (e.g., call carrier API).
 * @summary Create a shipment
 */
export const postAdminShipments = (
    postAdminShipmentsBody: PostAdminShipmentsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostAdminShipments201>(
      {url: `/admin/shipments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAdminShipmentsBody, signal
    },
      options);
    }



export const getPostAdminShipmentsMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminShipments>>, TError,{data: PostAdminShipmentsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminShipments>>, TError,{data: PostAdminShipmentsBody}, TContext> => {

const mutationKey = ['postAdminShipments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminShipments>>, {data: PostAdminShipmentsBody}> = (props) => {
          const {data} = props ?? {};

          return  postAdminShipments(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminShipmentsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminShipments>>>
    export type PostAdminShipmentsMutationBody = PostAdminShipmentsBody
    export type PostAdminShipmentsMutationError = UtilsResponse

    /**
 * @summary Create a shipment
 */
export const usePostAdminShipments = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminShipments>>, TError,{data: PostAdminShipmentsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminShipments>>,
        TError,
        {data: PostAdminShipmentsBody},
        TContext
      > => {
      return useMutation(getPostAdminShipmentsMutationOptions(options), queryClient);
    }

