/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminAuditLogsSummary200
} from './-admin-audit-logs-summary-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Audit log summary
 */
export const getAdminAuditLogsSummary = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetAdminAuditLogsSummary200>(
      {url: `/admin/audit-logs/summary`, method: 'GET', signal
    },
      options);
    }




export const getGetAdminAuditLogsSummaryQueryKey = () => {
    return [
    `/admin/audit-logs/summary`
    ] as const;
    }


export const getGetAdminAuditLogsSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminAuditLogsSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminAuditLogsSummary>>> = ({ signal }) => getAdminAuditLogsSummary(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminAuditLogsSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminAuditLogsSummary>>>
export type GetAdminAuditLogsSummaryQueryError = unknown


export function useGetAdminAuditLogsSummary<TData = Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAuditLogsSummary>>,
          TError,
          Awaited<ReturnType<typeof getAdminAuditLogsSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminAuditLogsSummary<TData = Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminAuditLogsSummary>>,
          TError,
          Awaited<ReturnType<typeof getAdminAuditLogsSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminAuditLogsSummary<TData = Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Audit log summary
 */

export function useGetAdminAuditLogsSummary<TData = Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAuditLogsSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminAuditLogsSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







