/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoAdminSalesFeedEvent {
  amount?: number;
  id?: string;
  subtitle?: string;
  timestamp?: number;
  title?: string;
  type?: string;
}

export interface DtoAdminDashboardSeriesPoint {
  date?: string;
  orders?: number;
  revenue?: number;
}

export interface DtoAdminDashboardStatusCount {
  count?: number;
  status?: string;
}

export interface DtoAdminSalesFeedSnapshotResponse {
  generated_at?: string;
  recent_events?: DtoAdminSalesFeedEvent[];
  revenue_series?: DtoAdminDashboardSeriesPoint[];
  status_counts?: DtoAdminDashboardStatusCount[];
  total_orders_today?: number;
  total_revenue_today?: number;
}

export type GetAdminSalesFeedSnapshot200 = UtilsResponse & {
  data?: DtoAdminSalesFeedSnapshotResponse;
};

