/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoCouponListResponse,
  GetAdminCouponsParams,
  UtilsResponse
} from './-admin-coupons-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a paginated list of all coupons for admin management with optional status filters
 * @summary List coupons (admin)
 */
export const getAdminCoupons = (
    params?: GetAdminCouponsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DtoCouponListResponse>(
      {url: `/admin/coupons`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetAdminCouponsQueryKey = (params?: GetAdminCouponsParams,) => {
    return [
    `/admin/coupons`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminCouponsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminCoupons>>, TError = UtilsResponse>(params?: GetAdminCouponsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCoupons>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminCouponsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminCoupons>>> = ({ signal }) => getAdminCoupons(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminCoupons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminCouponsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminCoupons>>>
export type GetAdminCouponsQueryError = UtilsResponse


export function useGetAdminCoupons<TData = Awaited<ReturnType<typeof getAdminCoupons>>, TError = UtilsResponse>(
 params: undefined |  GetAdminCouponsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCoupons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCoupons>>,
          TError,
          Awaited<ReturnType<typeof getAdminCoupons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCoupons<TData = Awaited<ReturnType<typeof getAdminCoupons>>, TError = UtilsResponse>(
 params?: GetAdminCouponsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCoupons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminCoupons>>,
          TError,
          Awaited<ReturnType<typeof getAdminCoupons>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminCoupons<TData = Awaited<ReturnType<typeof getAdminCoupons>>, TError = UtilsResponse>(
 params?: GetAdminCouponsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCoupons>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List coupons (admin)
 */

export function useGetAdminCoupons<TData = Awaited<ReturnType<typeof getAdminCoupons>>, TError = UtilsResponse>(
 params?: GetAdminCouponsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCoupons>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminCouponsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







