/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCreateRoleRequest,
  PostAdminRoles201
} from './-admin-roles-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create role
 */
export const postAdminRoles = (
    dtoCreateRoleRequest: DtoCreateRoleRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostAdminRoles201>(
      {url: `/admin/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoCreateRoleRequest, signal
    },
      options);
    }



export const getPostAdminRolesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminRoles>>, TError,{data: DtoCreateRoleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminRoles>>, TError,{data: DtoCreateRoleRequest}, TContext> => {

const mutationKey = ['postAdminRoles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminRoles>>, {data: DtoCreateRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAdminRoles(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminRolesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminRoles>>>
    export type PostAdminRolesMutationBody = DtoCreateRoleRequest
    export type PostAdminRolesMutationError = unknown

    /**
 * @summary Create role
 */
export const usePostAdminRoles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminRoles>>, TError,{data: DtoCreateRoleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminRoles>>,
        TError,
        {data: DtoCreateRoleRequest},
        TContext
      > => {
      return useMutation(getPostAdminRolesMutationOptions(options), queryClient);
    }

