/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export type DtoUpdateInvoiceStatusRequestStatus = typeof DtoUpdateInvoiceStatusRequestStatus[keyof typeof DtoUpdateInvoiceStatusRequestStatus];


export const DtoUpdateInvoiceStatusRequestStatus = {
  draft: 'draft',
  issued: 'issued',
  paid: 'paid',
  void: 'void',
  refunded: 'refunded',
} as const;

export interface DtoUpdateInvoiceStatusRequest {
  status: DtoUpdateInvoiceStatusRequestStatus;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

