/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoCategoryResponse {
  description?: string;
  id?: number;
  is_active?: boolean;
  level?: number;
  name?: string;
  parent_id?: number;
  path?: string;
  slug?: string;
}

export interface DtoStoreResponse {
  banner_url?: string;
  categories?: DtoCategoryResponse[];
  description?: string;
  follower_count?: number;
  id?: number;
  is_followed?: boolean;
  is_verified?: boolean;
  joined_at?: string;
  location?: string;
  logo_url?: string;
  name?: string;
  rating?: number;
  return_policy?: string;
  review_count?: number;
  shipping_info?: string;
  slug?: string;
}

export type GetAdminStoresId200 = UtilsResponse & {
  data?: DtoStoreResponse;
};

