/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminInventoryOverview200,
  UtilsResponse
} from './-admin-inventory-overview-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns low-stock, out-of-stock, and waitlist totals for the admin inventory dashboard
 * @summary Inventory overview KPIs
 */
export const getAdminInventoryOverview = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetAdminInventoryOverview200>(
      {url: `/admin/inventory/overview`, method: 'GET', signal
    },
      options);
    }




export const getGetAdminInventoryOverviewQueryKey = () => {
    return [
    `/admin/inventory/overview`
    ] as const;
    }


export const getGetAdminInventoryOverviewQueryOptions = <TData = Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError = UtilsResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminInventoryOverviewQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminInventoryOverview>>> = ({ signal }) => getAdminInventoryOverview(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminInventoryOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminInventoryOverview>>>
export type GetAdminInventoryOverviewQueryError = UtilsResponse


export function useGetAdminInventoryOverview<TData = Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError = UtilsResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminInventoryOverview>>,
          TError,
          Awaited<ReturnType<typeof getAdminInventoryOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminInventoryOverview<TData = Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminInventoryOverview>>,
          TError,
          Awaited<ReturnType<typeof getAdminInventoryOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminInventoryOverview<TData = Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Inventory overview KPIs
 */

export function useGetAdminInventoryOverview<TData = Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryOverview>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminInventoryOverviewQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







