/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCategorySingleResponse,
  DtoCreateCategoryRequest,
  UtilsResponse
} from './-admin-categories-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a new product category. Only accessible by users with the "admin" role.
 * @summary Create a new category
 */
export const postAdminCategories = (
    dtoCreateCategoryRequest: DtoCreateCategoryRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DtoCategorySingleResponse>(
      {url: `/admin/categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoCreateCategoryRequest, signal
    },
      options);
    }



export const getPostAdminCategoriesMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminCategories>>, TError,{data: DtoCreateCategoryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminCategories>>, TError,{data: DtoCreateCategoryRequest}, TContext> => {

const mutationKey = ['postAdminCategories'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminCategories>>, {data: DtoCreateCategoryRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAdminCategories(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminCategoriesMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminCategories>>>
    export type PostAdminCategoriesMutationBody = DtoCreateCategoryRequest
    export type PostAdminCategoriesMutationError = UtilsResponse

    /**
 * @summary Create a new category
 */
export const usePostAdminCategories = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminCategories>>, TError,{data: DtoCreateCategoryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminCategories>>,
        TError,
        {data: DtoCreateCategoryRequest},
        TContext
      > => {
      return useMutation(getPostAdminCategoriesMutationOptions(options), queryClient);
    }

