/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminReviewsParams,
  UtilsResponse
} from './-admin-reviews-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Paginated list of product reviews with optional status and product filters
 * @summary List product reviews (admin)
 */
export const getAdminReviews = (
    params?: GetAdminReviewsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/admin/reviews`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetAdminReviewsQueryKey = (params?: GetAdminReviewsParams,) => {
    return [
    `/admin/reviews`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminReviewsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminReviews>>, TError = unknown>(params?: GetAdminReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminReviews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminReviewsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminReviews>>> = ({ signal }) => getAdminReviews(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminReviews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminReviewsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminReviews>>>
export type GetAdminReviewsQueryError = unknown


export function useGetAdminReviews<TData = Awaited<ReturnType<typeof getAdminReviews>>, TError = unknown>(
 params: undefined |  GetAdminReviewsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminReviews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminReviews>>,
          TError,
          Awaited<ReturnType<typeof getAdminReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminReviews<TData = Awaited<ReturnType<typeof getAdminReviews>>, TError = unknown>(
 params?: GetAdminReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminReviews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminReviews>>,
          TError,
          Awaited<ReturnType<typeof getAdminReviews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminReviews<TData = Awaited<ReturnType<typeof getAdminReviews>>, TError = unknown>(
 params?: GetAdminReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminReviews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List product reviews (admin)
 */

export function useGetAdminReviews<TData = Awaited<ReturnType<typeof getAdminReviews>>, TError = unknown>(
 params?: GetAdminReviewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminReviews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminReviewsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







