/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoUpdateRoleRequest,
  PutAdminRolesId200
} from './-admin-roles-{id}-put.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Update role
 */
export const putAdminRolesId = (
    id: number,
    dtoUpdateRoleRequest: DtoUpdateRoleRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PutAdminRolesId200>(
      {url: `/admin/roles/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dtoUpdateRoleRequest, signal
    },
      options);
    }



export const getPutAdminRolesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminRolesId>>, TError,{id: number;data: DtoUpdateRoleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putAdminRolesId>>, TError,{id: number;data: DtoUpdateRoleRequest}, TContext> => {

const mutationKey = ['putAdminRolesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAdminRolesId>>, {id: number;data: DtoUpdateRoleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putAdminRolesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutAdminRolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putAdminRolesId>>>
    export type PutAdminRolesIdMutationBody = DtoUpdateRoleRequest
    export type PutAdminRolesIdMutationError = unknown

    /**
 * @summary Update role
 */
export const usePutAdminRolesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAdminRolesId>>, TError,{id: number;data: DtoUpdateRoleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAdminRolesId>>,
        TError,
        {id: number;data: DtoUpdateRoleRequest},
        TContext
      > => {
      return useMutation(getPutAdminRolesIdMutationOptions(options), queryClient);
    }

