/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoAdminDashboardKPI {
  change_percent?: number;
  previous_value?: number;
  value?: number;
}

export interface DtoAdminDashboardKPIs {
  avg_order_value?: DtoAdminDashboardKPI;
  new_customers?: DtoAdminDashboardKPI;
  orders?: DtoAdminDashboardKPI;
  revenue?: DtoAdminDashboardKPI;
}

export interface DtoAdminDashboardLowStockProduct {
  id?: number;
  name?: string;
  sku?: string;
  stock?: number;
  threshold?: number;
}

export interface DtoAdminDashboardStatusCount {
  count?: number;
  status?: string;
}

export interface DtoAdminStatsResponse {
  active_users?: number;
  admin_users?: number;
  low_stock_products?: number;
  pending_orders?: number;
  total_active_products?: number;
  total_orders?: number;
  total_revenue?: number;
  total_users?: number;
  total_wallet_balance?: number;
}

export interface DtoAdminDashboardRecentOrder {
  created_at?: string;
  currency?: string;
  customer_email?: string;
  customer_name?: string;
  id?: number;
  order_number?: string;
  status?: string;
  total_amount?: number;
}

export interface DtoAdminDashboardSeriesPoint {
  date?: string;
  orders?: number;
  revenue?: number;
}

export interface DtoAdminDashboardTopProduct {
  id?: number;
  name?: string;
  revenue?: number;
  sku?: string;
  stock?: number;
  units_sold?: number;
}

export interface DtoAdminDashboardOverviewResponse {
  generated_at?: string;
  kpis?: DtoAdminDashboardKPIs;
  low_stock_products?: DtoAdminDashboardLowStockProduct[];
  orders_by_status?: DtoAdminDashboardStatusCount[];
  period?: string;
  platform?: DtoAdminStatsResponse;
  recent_orders?: DtoAdminDashboardRecentOrder[];
  revenue_series?: DtoAdminDashboardSeriesPoint[];
  top_products?: DtoAdminDashboardTopProduct[];
}

export type GetAdminDashboardOverviewParams = {
/**
 * Period: 7d, 30d, or 90d (default 30d)
 */
period?: string;
};

export type GetAdminDashboardOverview200 = UtilsResponse & {
  data?: DtoAdminDashboardOverviewResponse;
};

