/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export type GetAdminWebhooksParams = {
/**
 * Items per page (default 20)
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
/**
 * Filter by source (e.g. stripe)
 */
source?: string;
/**
 * Filter by event type
 */
event_type?: string;
/**
 * Filter by status (received|processed|failed)
 */
status?: string;
};

