/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoAiStatusResponse {
  enabled?: boolean;
  model?: string;
  provider?: string;
}

export type GetAdminAiStatus200 = UtilsResponse & {
  data?: DtoAiStatusResponse;
};

