/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminInventoryAdjustmentsRecent200,
  GetAdminInventoryAdjustmentsRecentParams,
  UtilsResponse
} from './-admin-inventory-adjustments-recent-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Latest stock movements across all products
 * @summary Recent inventory adjustments
 */
export const getAdminInventoryAdjustmentsRecent = (
    params?: GetAdminInventoryAdjustmentsRecentParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetAdminInventoryAdjustmentsRecent200>(
      {url: `/admin/inventory/adjustments/recent`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetAdminInventoryAdjustmentsRecentQueryKey = (params?: GetAdminInventoryAdjustmentsRecentParams,) => {
    return [
    `/admin/inventory/adjustments/recent`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminInventoryAdjustmentsRecentQueryOptions = <TData = Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError = UtilsResponse>(params?: GetAdminInventoryAdjustmentsRecentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminInventoryAdjustmentsRecentQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>> = ({ signal }) => getAdminInventoryAdjustmentsRecent(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminInventoryAdjustmentsRecentQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>>
export type GetAdminInventoryAdjustmentsRecentQueryError = UtilsResponse


export function useGetAdminInventoryAdjustmentsRecent<TData = Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError = UtilsResponse>(
 params: undefined |  GetAdminInventoryAdjustmentsRecentParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>,
          TError,
          Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminInventoryAdjustmentsRecent<TData = Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError = UtilsResponse>(
 params?: GetAdminInventoryAdjustmentsRecentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>,
          TError,
          Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminInventoryAdjustmentsRecent<TData = Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError = UtilsResponse>(
 params?: GetAdminInventoryAdjustmentsRecentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Recent inventory adjustments
 */

export function useGetAdminInventoryAdjustmentsRecent<TData = Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError = UtilsResponse>(
 params?: GetAdminInventoryAdjustmentsRecentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminInventoryAdjustmentsRecent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminInventoryAdjustmentsRecentQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







