/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UtilsResponse
} from './-admin-invoices-{id}-send-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Email invoice to customer (admin)
 */
export const postAdminInvoicesIdSend = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/admin/invoices/${id}/send`, method: 'POST', signal
    },
      options);
    }



export const getPostAdminInvoicesIdSendMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminInvoicesIdSend>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminInvoicesIdSend>>, TError,{id: number}, TContext> => {

const mutationKey = ['postAdminInvoicesIdSend'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminInvoicesIdSend>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postAdminInvoicesIdSend(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminInvoicesIdSendMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminInvoicesIdSend>>>

    export type PostAdminInvoicesIdSendMutationError = unknown

    /**
 * @summary Email invoice to customer (admin)
 */
export const usePostAdminInvoicesIdSend = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminInvoicesIdSend>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminInvoicesIdSend>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostAdminInvoicesIdSendMutationOptions(options), queryClient);
    }

