/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCreateMenuItemRequest,
  PostAdminMenuItems201,
  UtilsResponse
} from './-admin-menu-items-post.schemas';

import { customInstance } from '../lib/api/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Adds a new menu item (can be top-level or child of another item)
 * @summary Create a new menu item
 */
export const postAdminMenuItems = (
  dtoCreateMenuItemRequest: DtoCreateMenuItemRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PostAdminMenuItems201>(
    {
      url: `/admin/menu/items`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: dtoCreateMenuItemRequest,
      signal
    },
    options
  );
};

export const getPostAdminMenuItemsMutationOptions = <
  TError = UtilsResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAdminMenuItems>>,
    TError,
    { data: DtoCreateMenuItemRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAdminMenuItems>>,
  TError,
  { data: DtoCreateMenuItemRequest },
  TContext
> => {
  const mutationKey = ['postAdminMenuItems'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAdminMenuItems>>,
    { data: DtoCreateMenuItemRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAdminMenuItems(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAdminMenuItemsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAdminMenuItems>>
>;
export type PostAdminMenuItemsMutationBody = DtoCreateMenuItemRequest;
export type PostAdminMenuItemsMutationError = UtilsResponse;

/**
 * @summary Create a new menu item
 */
export const usePostAdminMenuItems = <TError = UtilsResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAdminMenuItems>>,
      TError,
      { data: DtoCreateMenuItemRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postAdminMenuItems>>,
  TError,
  { data: DtoCreateMenuItemRequest },
  TContext
> => {
  return useMutation(getPostAdminMenuItemsMutationOptions(options), queryClient);
};
