/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PostAdminImportProducts200,
  PostAdminImportProductsBody,
  PostAdminImportProductsParams,
  UtilsResponse
} from './-admin-import-products-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Upload an .xlsx file. Row 1 must be the header (name,sku,price,stock,description,status,category_id,brand_id,store_id,compare_at_price,barcode,low_stock_threshold,weight). Returns per-row result.
 * @summary Import products from Excel (admin)
 */
export const postAdminImportProducts = (
    postAdminImportProductsBody?: PostAdminImportProductsBody,
    params?: PostAdminImportProductsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {

      const formData = new FormData();
if(postAdminImportProductsBody?.file !== undefined) {
 formData.append(`file`, postAdminImportProductsBody.file);
 }

      return customInstance<PostAdminImportProducts200>(
      {url: `/admin/import/products`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params, signal
    },
      options);
    }



export const getPostAdminImportProductsMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminImportProducts>>, TError,{data?: PostAdminImportProductsBody;params?: PostAdminImportProductsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminImportProducts>>, TError,{data?: PostAdminImportProductsBody;params?: PostAdminImportProductsParams}, TContext> => {

const mutationKey = ['postAdminImportProducts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminImportProducts>>, {data?: PostAdminImportProductsBody;params?: PostAdminImportProductsParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postAdminImportProducts(data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminImportProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminImportProducts>>>
    export type PostAdminImportProductsMutationBody = PostAdminImportProductsBody | undefined
    export type PostAdminImportProductsMutationError = UtilsResponse

    /**
 * @summary Import products from Excel (admin)
 */
export const usePostAdminImportProducts = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminImportProducts>>, TError,{data?: PostAdminImportProductsBody;params?: PostAdminImportProductsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminImportProducts>>,
        TError,
        {data?: PostAdminImportProductsBody;params?: PostAdminImportProductsParams},
        TContext
      > => {
      return useMutation(getPostAdminImportProductsMutationOptions(options), queryClient);
    }

