/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoImportRowResult {
  /** human-readable reason (when status=failed/skipped) */
  error?: string;
  /** ID of the created record (when status=created) */
  id?: number;
  /** display value from the row for easy identification */
  name?: string;
  /** 1-based Excel row number (row 1 = header) */
  row?: number;
  /** "created" | "skipped" | "failed" */
  status?: string;
}

export interface DtoImportSummary {
  /** successfully inserted */
  created?: number;
  /** validation or DB errors */
  failed?: number;
  /** per-row detail */
  rows?: DtoImportRowResult[];
  /** intentionally skipped (e.g. empty row) */
  skipped?: number;
  /** data rows parsed (header excluded) */
  total_rows?: number;
}

export type PostAdminImportCategoriesBody = {
  /** Excel file (.xlsx) */
  file: Blob;
};

export type PostAdminImportCategories200 = UtilsResponse & {
  data?: DtoImportSummary;
};

