/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAdminSalesFeedSnapshot200,
  UtilsResponse
} from './-admin-sales-feed-snapshot-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns today's order totals, status breakdown, revenue series, and recent feed events.
 * @summary Live sales feed snapshot
 */
export const getAdminSalesFeedSnapshot = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetAdminSalesFeedSnapshot200>(
      {url: `/admin/sales-feed/snapshot`, method: 'GET', signal
    },
      options);
    }




export const getGetAdminSalesFeedSnapshotQueryKey = () => {
    return [
    `/admin/sales-feed/snapshot`
    ] as const;
    }


export const getGetAdminSalesFeedSnapshotQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError = UtilsResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSalesFeedSnapshotQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>> = ({ signal }) => getAdminSalesFeedSnapshot(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminSalesFeedSnapshotQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>>
export type GetAdminSalesFeedSnapshotQueryError = UtilsResponse


export function useGetAdminSalesFeedSnapshot<TData = Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError = UtilsResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>,
          TError,
          Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSalesFeedSnapshot<TData = Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>,
          TError,
          Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminSalesFeedSnapshot<TData = Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Live sales feed snapshot
 */

export function useGetAdminSalesFeedSnapshot<TData = Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminSalesFeedSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminSalesFeedSnapshotQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







