/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PutAdminShipmentsIdStatusBody,
  UtilsResponse
} from './-admin-shipments-{id}-status-put.schemas';

import { customInstance } from '../lib/api/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Updates the status of a shipment and sends real-time notifications.
 * @summary Update shipment status (admin)
 */
export const putAdminShipmentsIdStatus = (
  id: number,
  putAdminShipmentsIdStatusBody: PutAdminShipmentsIdStatusBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UtilsResponse>(
    {
      url: `/admin/shipments/${id}/status`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putAdminShipmentsIdStatusBody,
      signal
    },
    options
  );
};

export const getPutAdminShipmentsIdStatusMutationOptions = <
  TError = UtilsResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAdminShipmentsIdStatus>>,
    TError,
    { id: number; data: PutAdminShipmentsIdStatusBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putAdminShipmentsIdStatus>>,
  TError,
  { id: number; data: PutAdminShipmentsIdStatusBody },
  TContext
> => {
  const mutationKey = ['putAdminShipmentsIdStatus'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putAdminShipmentsIdStatus>>,
    { id: number; data: PutAdminShipmentsIdStatusBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putAdminShipmentsIdStatus(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutAdminShipmentsIdStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAdminShipmentsIdStatus>>
>;
export type PutAdminShipmentsIdStatusMutationBody = PutAdminShipmentsIdStatusBody;
export type PutAdminShipmentsIdStatusMutationError = UtilsResponse;

/**
 * @summary Update shipment status (admin)
 */
export const usePutAdminShipmentsIdStatus = <TError = UtilsResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putAdminShipmentsIdStatus>>,
      TError,
      { id: number; data: PutAdminShipmentsIdStatusBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof putAdminShipmentsIdStatus>>,
  TError,
  { id: number; data: PutAdminShipmentsIdStatusBody },
  TContext
> => {
  return useMutation(getPutAdminShipmentsIdStatusMutationOptions(options), queryClient);
};
