/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export type DtoBulkAdjustInventoryRequestReason = typeof DtoBulkAdjustInventoryRequestReason[keyof typeof DtoBulkAdjustInventoryRequestReason];


export const DtoBulkAdjustInventoryRequestReason = {
  receive: 'receive',
  correction: 'correction',
  damage: 'damage',
  shrinkage: 'shrinkage',
  cycle_count: 'cycle_count',
  other: 'other',
} as const;

export interface DtoBulkInventoryAdjustRow {
  delta: number;
  /** @maxLength 200 */
  note?: string;
  /**
     * @minLength 1
     * @maxLength 64
     */
  sku: string;
}

export interface DtoBulkAdjustInventoryRequest {
  reason: DtoBulkAdjustInventoryRequestReason;
  /**
     * @minItems 1
     * @maxItems 500
     */
  rows: DtoBulkInventoryAdjustRow[];
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoBulkInventoryAdjustRowResult {
  message?: string;
  product_id?: number;
  sku?: string;
  stock?: number;
  success?: boolean;
}

export interface DtoBulkAdjustInventoryResponse {
  applied?: number;
  failed?: number;
  rows?: DtoBulkInventoryAdjustRowResult[];
}

export type PostAdminInventoryBulkAdjust200 = UtilsResponse & {
  data?: DtoBulkAdjustInventoryResponse;
};

