/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UtilsResponse
} from './-admin-stores-{id}-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Soft delete a store (admin only)
 * @summary Delete store
 */
export const deleteAdminStoresId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/admin/stores/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteAdminStoresIdMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminStoresId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminStoresId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteAdminStoresId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminStoresId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminStoresId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminStoresIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminStoresId>>>

    export type DeleteAdminStoresIdMutationError = UtilsResponse

    /**
 * @summary Delete store
 */
export const useDeleteAdminStoresId = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminStoresId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminStoresId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteAdminStoresIdMutationOptions(options), queryClient);
    }

