/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoAiGenerateRequest,
  PostAdminAiGenerate200,
  UtilsResponse
} from './-admin-ai-generate-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Generates product description, SEO metadata, or coupon copy for staff
 * @summary Generate AI copy
 */
export const postAdminAiGenerate = (
    dtoAiGenerateRequest: DtoAiGenerateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostAdminAiGenerate200>(
      {url: `/admin/ai/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoAiGenerateRequest, signal
    },
      options);
    }



export const getPostAdminAiGenerateMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminAiGenerate>>, TError,{data: DtoAiGenerateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminAiGenerate>>, TError,{data: DtoAiGenerateRequest}, TContext> => {

const mutationKey = ['postAdminAiGenerate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminAiGenerate>>, {data: DtoAiGenerateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAdminAiGenerate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminAiGenerateMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminAiGenerate>>>
    export type PostAdminAiGenerateMutationBody = DtoAiGenerateRequest
    export type PostAdminAiGenerateMutationError = UtilsResponse

    /**
 * @summary Generate AI copy
 */
export const usePostAdminAiGenerate = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminAiGenerate>>, TError,{data: DtoAiGenerateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminAiGenerate>>,
        TError,
        {data: DtoAiGenerateRequest},
        TContext
      > => {
      return useMutation(getPostAdminAiGenerateMutationOptions(options), queryClient);
    }

