/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoRoleResponse {
  created_at?: string;
  description?: string;
  id?: number;
  is_system?: boolean;
  name?: string;
  permission_count?: number;
  permission_ids?: number[];
  permission_keys?: string[];
  slug?: string;
  updated_at?: string;
  user_count?: number;
}

export type GetAdminRolesId200 = UtilsResponse & {
  data?: DtoRoleResponse;
};

