/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoAdjustInventoryRequest,
  PostAdminInventoryAdjust200,
  UtilsResponse
} from './-admin-inventory-adjust-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Apply a signed stock delta with reason (receive, correction, damage, etc.)
 * @summary Adjust product stock
 */
export const postAdminInventoryAdjust = (
    dtoAdjustInventoryRequest: DtoAdjustInventoryRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostAdminInventoryAdjust200>(
      {url: `/admin/inventory/adjust`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoAdjustInventoryRequest, signal
    },
      options);
    }



export const getPostAdminInventoryAdjustMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminInventoryAdjust>>, TError,{data: DtoAdjustInventoryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminInventoryAdjust>>, TError,{data: DtoAdjustInventoryRequest}, TContext> => {

const mutationKey = ['postAdminInventoryAdjust'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminInventoryAdjust>>, {data: DtoAdjustInventoryRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAdminInventoryAdjust(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminInventoryAdjustMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminInventoryAdjust>>>
    export type PostAdminInventoryAdjustMutationBody = DtoAdjustInventoryRequest
    export type PostAdminInventoryAdjustMutationError = UtilsResponse

    /**
 * @summary Adjust product stock
 */
export const usePostAdminInventoryAdjust = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminInventoryAdjust>>, TError,{data: DtoAdjustInventoryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminInventoryAdjust>>,
        TError,
        {data: DtoAdjustInventoryRequest},
        TContext
      > => {
      return useMutation(getPostAdminInventoryAdjustMutationOptions(options), queryClient);
    }

