/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UtilsResponse
} from './-admin-workflows-{id}-transitions-{transitionId}-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Delete workflow transition (admin)
 */
export const deleteAdminWorkflowsIdTransitionsTransitionId = (
    id: number,
    transitionId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/admin/workflows/${id}/transitions/${transitionId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteAdminWorkflowsIdTransitionsTransitionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminWorkflowsIdTransitionsTransitionId>>, TError,{id: number;transitionId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminWorkflowsIdTransitionsTransitionId>>, TError,{id: number;transitionId: number}, TContext> => {

const mutationKey = ['deleteAdminWorkflowsIdTransitionsTransitionId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminWorkflowsIdTransitionsTransitionId>>, {id: number;transitionId: number}> = (props) => {
          const {id,transitionId} = props ?? {};

          return  deleteAdminWorkflowsIdTransitionsTransitionId(id,transitionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminWorkflowsIdTransitionsTransitionIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminWorkflowsIdTransitionsTransitionId>>>

    export type DeleteAdminWorkflowsIdTransitionsTransitionIdMutationError = unknown

    /**
 * @summary Delete workflow transition (admin)
 */
export const useDeleteAdminWorkflowsIdTransitionsTransitionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminWorkflowsIdTransitionsTransitionId>>, TError,{id: number;transitionId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminWorkflowsIdTransitionsTransitionId>>,
        TError,
        {id: number;transitionId: number},
        TContext
      > => {
      return useMutation(getDeleteAdminWorkflowsIdTransitionsTransitionIdMutationOptions(options), queryClient);
    }

