/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoAiChatMessage {
  content: string;
  role: string;
}

export interface DtoAiChatRequest {
  /** @minItems 1 */
  messages: DtoAiChatMessage[];
  product_id: number;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoAiChatResponse {
  reply?: string;
  sources?: string[];
}

export type PostAiChat200 = UtilsResponse & {
  data?: DtoAiChatResponse;
};

