/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoAiChatRequest,
  PostAiChat200,
  UtilsResponse
} from './-ai-chat-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Grounded product assistant chat for shoppers (guest or authenticated)
 * @summary Product AI chat
 */
export const postAiChat = (
    dtoAiChatRequest: DtoAiChatRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostAiChat200>(
      {url: `/ai/chat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoAiChatRequest, signal
    },
      options);
    }



export const getPostAiChatMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAiChat>>, TError,{data: DtoAiChatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAiChat>>, TError,{data: DtoAiChatRequest}, TContext> => {

const mutationKey = ['postAiChat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAiChat>>, {data: DtoAiChatRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAiChat(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAiChatMutationResult = NonNullable<Awaited<ReturnType<typeof postAiChat>>>
    export type PostAiChatMutationBody = DtoAiChatRequest
    export type PostAiChatMutationError = UtilsResponse

    /**
 * @summary Product AI chat
 */
export const usePostAiChat = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAiChat>>, TError,{data: DtoAiChatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAiChat>>,
        TError,
        {data: DtoAiChatRequest},
        TContext
      > => {
      return useMutation(getPostAiChatMutationOptions(options), queryClient);
    }

