/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoMessageResponse {
  message?: string;
  success?: boolean;
}

export type PostAuthLogoutBody = { [key: string]: unknown };

