/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoRegisterRequest {
  accept_privacy: boolean;
  accept_terms: boolean;
  email: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  first_name: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  last_name: string;
  /** @minLength 8 */
  password: string;
  phone?: string;
}

export interface DtoUserResponse {
  email?: string;
  first_name?: string;
  id?: number;
  last_name?: string;
  phone?: string;
  role?: string;
}

export interface DtoRegisterResponseData {
  access_token?: string;
  refresh_token?: string;
  user?: DtoUserResponse;
}

export interface DtoRegisterResponse {
  data?: DtoRegisterResponseData;
  message?: string;
  success?: boolean;
}

export interface DtoMessageResponse {
  message?: string;
  success?: boolean;
}

