/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UtilsResponse
} from './-brands-{id}-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Permanently deletes a brand by ID.
 * @summary Delete a brand
 */
export const deleteBrandsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/brands/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteBrandsIdMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBrandsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBrandsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteBrandsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBrandsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteBrandsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteBrandsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBrandsId>>>

    export type DeleteBrandsIdMutationError = UtilsResponse

    /**
 * @summary Delete a brand
 */
export const useDeleteBrandsId = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBrandsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBrandsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteBrandsIdMutationOptions(options), queryClient);
    }

