/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetBrandsId200,
  UtilsResponse
} from './-brands-{id}-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a single brand by its unique identifier.
 * @summary Get a brand by ID
 */
export const getBrandsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetBrandsId200>(
      {url: `/brands/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetBrandsIdQueryKey = (id: number,) => {
    return [
    `/brands/${id}`
    ] as const;
    }


export const getGetBrandsIdQueryOptions = <TData = Awaited<ReturnType<typeof getBrandsId>>, TError = UtilsResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBrandsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBrandsId>>> = ({ signal }) => getBrandsId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBrandsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getBrandsId>>>
export type GetBrandsIdQueryError = UtilsResponse


export function useGetBrandsId<TData = Awaited<ReturnType<typeof getBrandsId>>, TError = UtilsResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrandsId>>,
          TError,
          Awaited<ReturnType<typeof getBrandsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBrandsId<TData = Awaited<ReturnType<typeof getBrandsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrandsId>>,
          TError,
          Awaited<ReturnType<typeof getBrandsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBrandsId<TData = Awaited<ReturnType<typeof getBrandsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a brand by ID
 */

export function useGetBrandsId<TData = Awaited<ReturnType<typeof getBrandsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBrandsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







