/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoStateView {
  code?: string;
  color?: string;
  id?: number;
  is_final?: boolean;
  is_initial?: boolean;
  name?: string;
  sort_order?: number;
  text_color?: string;
}

export interface DtoBrandResponse {
  created_at?: string;
  description?: string;
  id?: number;
  logo_url?: string;
  name?: string;
  slug?: string;
  status?: string;
  updated_at?: string;
  workflow_state?: DtoStateView;
}

export interface DtoBrandListData {
  brands?: DtoBrandResponse[];
  limit?: number;
  page?: number;
  total?: number;
}

export interface DtoBrandListResponse {
  code?: number;
  data?: DtoBrandListData;
  message?: string;
  success?: boolean;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export type GetBrands200 = DtoBrandListResponse;

export type GetBrandsParams = {
  /**
   * Page number
   */
  page?: number;
  /**
   * Items per page
   */
  limit?: number;
  /**
   * Search by name or slug
   */
  search?: string;
  /**
   * Filter by status
   */
  status?: string;
};
