/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoUpdateBrandRequest {
  description?: string;
  logo_url?: string;
  name?: string;
  slug?: string;
  status?: string;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoBrandResponse {
  created_at?: string;
  description?: string;
  id?: number;
  logo_url?: string;
  name?: string;
  slug?: string;
  status?: string;
  updated_at?: string;
}

export type PutBrandsId200 = UtilsResponse & {
  data?: DtoBrandResponse;
};

