/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoEmptyResponse,
  UtilsResponse
} from './-cart-items-{id}-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Remove a specific item from the cart
 * @summary Remove cart item
 */
export const deleteCartItemsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DtoEmptyResponse>(
      {url: `/cart/items/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteCartItemsIdMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCartItemsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCartItemsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCartItemsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCartItemsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCartItemsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCartItemsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCartItemsId>>>

    export type DeleteCartItemsIdMutationError = UtilsResponse

    /**
 * @summary Remove cart item
 */
export const useDeleteCartItemsId = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCartItemsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCartItemsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCartItemsIdMutationOptions(options), queryClient);
    }

