/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoCategorySingleResponse,
  UtilsResponse
} from './-categories-{identifier}-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a single category. Accepts either a numeric ID or a URL slug.
 * @summary Get a category by ID or slug
 */
export const getCategoriesIdentifier = (
    identifier: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DtoCategorySingleResponse>(
      {url: `/categories/${identifier}`, method: 'GET', signal
    },
      options);
    }




export const getGetCategoriesIdentifierQueryKey = (identifier: string,) => {
    return [
    `/categories/${identifier}`
    ] as const;
    }


export const getGetCategoriesIdentifierQueryOptions = <TData = Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError = UtilsResponse>(identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCategoriesIdentifierQueryKey(identifier);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategoriesIdentifier>>> = ({ signal }) => getCategoriesIdentifier(identifier, requestOptions, signal);





   return  { queryKey, queryFn, enabled: identifier !== null && identifier !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCategoriesIdentifierQueryResult = NonNullable<Awaited<ReturnType<typeof getCategoriesIdentifier>>>
export type GetCategoriesIdentifierQueryError = UtilsResponse


export function useGetCategoriesIdentifier<TData = Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError = UtilsResponse>(
 identifier: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoriesIdentifier>>,
          TError,
          Awaited<ReturnType<typeof getCategoriesIdentifier>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategoriesIdentifier<TData = Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError = UtilsResponse>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoriesIdentifier>>,
          TError,
          Awaited<ReturnType<typeof getCategoriesIdentifier>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategoriesIdentifier<TData = Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError = UtilsResponse>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a category by ID or slug
 */

export function useGetCategoriesIdentifier<TData = Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError = UtilsResponse>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesIdentifier>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCategoriesIdentifierQueryOptions(identifier,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







