/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type { DtoCheckoutRequest, PostCheckout201, UtilsResponse } from './-checkout-post.schemas';

import { customInstance } from '../lib/api/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Converts the authenticated user's cart into an order, creates pending payment and shipment, and starts background fulfillment.
 * @summary Checkout
 */
export const postCheckout = (
  dtoCheckoutRequest: DtoCheckoutRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PostCheckout201>(
    {
      url: `/checkout`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: dtoCheckoutRequest,
      signal
    },
    options
  );
};

export const getPostCheckoutMutationOptions = <
  TError = UtilsResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCheckout>>,
    TError,
    { data: DtoCheckoutRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCheckout>>,
  TError,
  { data: DtoCheckoutRequest },
  TContext
> => {
  const mutationKey = ['postCheckout'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCheckout>>,
    { data: DtoCheckoutRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postCheckout(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCheckoutMutationResult = NonNullable<Awaited<ReturnType<typeof postCheckout>>>;
export type PostCheckoutMutationBody = DtoCheckoutRequest;
export type PostCheckoutMutationError = UtilsResponse;

/**
 * @summary Checkout
 */
export const usePostCheckout = <TError = UtilsResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCheckout>>,
      TError,
      { data: DtoCheckoutRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postCheckout>>,
  TError,
  { data: DtoCheckoutRequest },
  TContext
> => {
  return useMutation(getPostCheckoutMutationOptions(options), queryClient);
};
