/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export type DtoUpdateCollectionRequestStatus = typeof DtoUpdateCollectionRequestStatus[keyof typeof DtoUpdateCollectionRequestStatus];


export const DtoUpdateCollectionRequestStatus = {
  draft: 'draft',
  active: 'active',
  inactive: 'inactive',
  archived: 'archived',
} as const;

export interface DtoUpdateCollectionRequest {
  /** @maxLength 128 */
  cta_label?: string;
  /** @maxLength 2000 */
  description?: string;
  /** @maxLength 128 */
  eyebrow?: string;
  /** @maxLength 512 */
  href?: string;
  /** @maxLength 2048 */
  image_url?: string;
  preview_category_id?: number;
  preview_is_new?: boolean;
  /** @maxLength 64 */
  preview_sort?: string;
  /**
     * @minLength 2
     * @maxLength 128
     */
  slug?: string;
  sort_order?: number;
  status?: DtoUpdateCollectionRequestStatus;
  /**
     * @minLength 2
     * @maxLength 255
     */
  title?: string;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoStateView {
  code?: string;
  color?: string;
  id?: number;
  is_final?: boolean;
  is_initial?: boolean;
  name?: string;
  sort_order?: number;
  text_color?: string;
}

export interface DtoCollectionResponse {
  created_at?: string;
  cta_label?: string;
  description?: string;
  eyebrow?: string;
  href?: string;
  id?: number;
  image_url?: string;
  preview_category_id?: number;
  preview_is_new?: boolean;
  preview_sort?: string;
  slug?: string;
  sort_order?: number;
  status?: string;
  title?: string;
  updated_at?: string;
  workflow_state?: DtoStateView;
}

export type PutCollectionsId200 = UtilsResponse & {
  data?: DtoCollectionResponse;
};

