/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCollectionsId200,
  UtilsResponse
} from './-collections-{id}-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get a collection by ID
 */
export const getCollectionsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetCollectionsId200>(
      {url: `/collections/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetCollectionsIdQueryKey = (id: number,) => {
    return [
    `/collections/${id}`
    ] as const;
    }


export const getGetCollectionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getCollectionsId>>, TError = UtilsResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCollectionsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollectionsId>>> = ({ signal }) => getCollectionsId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCollectionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCollectionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCollectionsId>>>
export type GetCollectionsIdQueryError = UtilsResponse


export function useGetCollectionsId<TData = Awaited<ReturnType<typeof getCollectionsId>>, TError = UtilsResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionsId>>,
          TError,
          Awaited<ReturnType<typeof getCollectionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCollectionsId<TData = Awaited<ReturnType<typeof getCollectionsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionsId>>,
          TError,
          Awaited<ReturnType<typeof getCollectionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCollectionsId<TData = Awaited<ReturnType<typeof getCollectionsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a collection by ID
 */

export function useGetCollectionsId<TData = Awaited<ReturnType<typeof getCollectionsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCollectionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







