/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoValidateRequest {
  code: string;
  order_total: number;
}

export interface GormDeletedAt {
  time?: string;
  /** Valid is true if Time is not NULL */
  valid?: boolean;
}

export type ModelsCouponDiscountType = typeof ModelsCouponDiscountType[keyof typeof ModelsCouponDiscountType];


export const ModelsCouponDiscountType = {
  percentage: 'percentage',
  fixed: 'fixed',
} as const;

export interface ModelsWorkflowState {
  code?: string;
  color?: string;
  created_at?: string;
  description?: string;
  id?: number;
  is_final?: boolean;
  is_initial?: boolean;
  name?: string;
  sort_order?: number;
  text_color?: string;
  updated_at?: string;
  workflow_id?: number;
}

export interface ModelsCoupon {
  /**
     * @minLength 3
     * @maxLength 50
     */
  code: string;
  created_at?: string;
  deleted_at?: GormDeletedAt;
  description?: string;
  discount_type?: ModelsCouponDiscountType;
  discount_value?: number;
  end_date?: string;
  id?: number;
  is_active?: boolean;
  max_discount_amount?: number;
  minimum_order_amount?: number;
  start_date?: string;
  updated_at?: string;
  usage_limit?: number;
  used_count?: number;
  workflow_state?: ModelsWorkflowState;
  workflow_state_id?: number;
}

export interface DtoCouponValidateData {
  coupon?: ModelsCoupon;
  discount_amount?: number;
  final_total?: number;
}

export interface DtoCouponValidateResponse {
  code?: number;
  data?: DtoCouponValidateData;
  message?: string;
  success?: boolean;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

