/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoEmptyResponse,
  UtilsResponse
} from './-coupons-{id}-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Soft-deletes a coupon by ID. Only accessible by users with the "admin" role.
 * @summary Delete coupon
 */
export const deleteCouponsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DtoEmptyResponse>(
      {url: `/coupons/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteCouponsIdMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouponsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCouponsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCouponsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCouponsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCouponsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCouponsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCouponsId>>>

    export type DeleteCouponsIdMutationError = UtilsResponse

    /**
 * @summary Delete coupon
 */
export const useDeleteCouponsId = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouponsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCouponsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCouponsIdMutationOptions(options), queryClient);
    }

