/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export type DtoCreateCouponRequestDiscountType =
  (typeof DtoCreateCouponRequestDiscountType)[keyof typeof DtoCreateCouponRequestDiscountType];

export const DtoCreateCouponRequestDiscountType = {
  percentage: 'percentage',
  fixed: 'fixed'
} as const;

export interface DtoCreateCouponRequest {
  /**
   * @minLength 3
   * @maxLength 50
   */
  code: string;
  description?: string;
  discount_type: DtoCreateCouponRequestDiscountType;
  discount_value: number;
  end_date: string;
  max_discount_amount?: number;
  minimum_order_amount?: number;
  start_date: string;
  usage_limit?: number;
}

export interface GormDeletedAt {
  time?: string;
  /** Valid is true if Time is not NULL */
  valid?: boolean;
}

export type ModelsCouponDiscountType =
  (typeof ModelsCouponDiscountType)[keyof typeof ModelsCouponDiscountType];

export const ModelsCouponDiscountType = {
  percentage: 'percentage',
  fixed: 'fixed'
} as const;

export interface ModelsCoupon {
  /**
   * @minLength 3
   * @maxLength 50
   */
  code: string;
  created_at?: string;
  deleted_at?: GormDeletedAt;
  description?: string;
  discount_type?: ModelsCouponDiscountType;
  discount_value?: number;
  end_date?: string;
  id?: number;
  is_active?: boolean;
  max_discount_amount?: number;
  minimum_order_amount?: number;
  start_date?: string;
  updated_at?: string;
  usage_limit?: number;
  used_count?: number;
}

export interface DtoCouponData {
  coupon?: ModelsCoupon;
}

export interface DtoCouponSingleResponse {
  code?: number;
  data?: DtoCouponData;
  message?: string;
  success?: boolean;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}
