/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetHealthReady200,
  GetHealthReady503
} from './-health-ready-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns 200 when database (and Redis if configured) are reachable.
 * @summary Readiness probe
 */
export const getHealthReady = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetHealthReady200>(
      {url: `/health/ready`, method: 'GET', signal
    },
      options);
    }




export const getGetHealthReadyQueryKey = () => {
    return [
    `/health/ready`
    ] as const;
    }


export const getGetHealthReadyQueryOptions = <TData = Awaited<ReturnType<typeof getHealthReady>>, TError = GetHealthReady503>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthReady>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthReadyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthReady>>> = ({ signal }) => getHealthReady(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealthReady>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthReadyQueryResult = NonNullable<Awaited<ReturnType<typeof getHealthReady>>>
export type GetHealthReadyQueryError = GetHealthReady503


export function useGetHealthReady<TData = Awaited<ReturnType<typeof getHealthReady>>, TError = GetHealthReady503>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthReady>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthReady>>,
          TError,
          Awaited<ReturnType<typeof getHealthReady>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealthReady<TData = Awaited<ReturnType<typeof getHealthReady>>, TError = GetHealthReady503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthReady>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthReady>>,
          TError,
          Awaited<ReturnType<typeof getHealthReady>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealthReady<TData = Awaited<ReturnType<typeof getHealthReady>>, TError = GetHealthReady503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthReady>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness probe
 */

export function useGetHealthReady<TData = Awaited<ReturnType<typeof getHealthReady>>, TError = GetHealthReady503>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthReady>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthReadyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







