/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export type GetHealthReady200 = { [key: string]: unknown };

export type GetHealthReady503 = { [key: string]: unknown };

