/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoUpsertNavMenuRequest,
  PostNavMenus201
} from './-nav-menus-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create navigation menu
 */
export const postNavMenus = (
    dtoUpsertNavMenuRequest: DtoUpsertNavMenuRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostNavMenus201>(
      {url: `/nav-menus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoUpsertNavMenuRequest, signal
    },
      options);
    }



export const getPostNavMenusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postNavMenus>>, TError,{data: DtoUpsertNavMenuRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postNavMenus>>, TError,{data: DtoUpsertNavMenuRequest}, TContext> => {

const mutationKey = ['postNavMenus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postNavMenus>>, {data: DtoUpsertNavMenuRequest}> = (props) => {
          const {data} = props ?? {};

          return  postNavMenus(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostNavMenusMutationResult = NonNullable<Awaited<ReturnType<typeof postNavMenus>>>
    export type PostNavMenusMutationBody = DtoUpsertNavMenuRequest
    export type PostNavMenusMutationError = unknown

    /**
 * @summary Create navigation menu
 */
export const usePostNavMenus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postNavMenus>>, TError,{data: DtoUpsertNavMenuRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postNavMenus>>,
        TError,
        {data: DtoUpsertNavMenuRequest},
        TContext
      > => {
      return useMutation(getPostNavMenusMutationOptions(options), queryClient);
    }

