/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoUpsertNavMenuRequest,
  PutNavMenusId200
} from './-nav-menus-{id}-put.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Update navigation menu
 */
export const putNavMenusId = (
    id: number,
    dtoUpsertNavMenuRequest: DtoUpsertNavMenuRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PutNavMenusId200>(
      {url: `/nav-menus/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dtoUpsertNavMenuRequest, signal
    },
      options);
    }



export const getPutNavMenusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putNavMenusId>>, TError,{id: number;data: DtoUpsertNavMenuRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putNavMenusId>>, TError,{id: number;data: DtoUpsertNavMenuRequest}, TContext> => {

const mutationKey = ['putNavMenusId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putNavMenusId>>, {id: number;data: DtoUpsertNavMenuRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putNavMenusId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutNavMenusIdMutationResult = NonNullable<Awaited<ReturnType<typeof putNavMenusId>>>
    export type PutNavMenusIdMutationBody = DtoUpsertNavMenuRequest
    export type PutNavMenusIdMutationError = unknown

    /**
 * @summary Update navigation menu
 */
export const usePutNavMenusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putNavMenusId>>, TError,{id: number;data: DtoUpsertNavMenuRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putNavMenusId>>,
        TError,
        {id: number;data: DtoUpsertNavMenuRequest},
        TContext
      > => {
      return useMutation(getPutNavMenusIdMutationOptions(options), queryClient);
    }

