/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetNavMenusId200
} from './-nav-menus-{id}-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get one navigation menu
 */
export const getNavMenusId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetNavMenusId200>(
      {url: `/nav-menus/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetNavMenusIdQueryKey = (id: number,) => {
    return [
    `/nav-menus/${id}`
    ] as const;
    }


export const getGetNavMenusIdQueryOptions = <TData = Awaited<ReturnType<typeof getNavMenusId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNavMenusId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNavMenusIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNavMenusId>>> = ({ signal }) => getNavMenusId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNavMenusId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNavMenusIdQueryResult = NonNullable<Awaited<ReturnType<typeof getNavMenusId>>>
export type GetNavMenusIdQueryError = unknown


export function useGetNavMenusId<TData = Awaited<ReturnType<typeof getNavMenusId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNavMenusId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNavMenusId>>,
          TError,
          Awaited<ReturnType<typeof getNavMenusId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNavMenusId<TData = Awaited<ReturnType<typeof getNavMenusId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNavMenusId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNavMenusId>>,
          TError,
          Awaited<ReturnType<typeof getNavMenusId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNavMenusId<TData = Awaited<ReturnType<typeof getNavMenusId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNavMenusId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get one navigation menu
 */

export function useGetNavMenusId<TData = Awaited<ReturnType<typeof getNavMenusId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNavMenusId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNavMenusIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







