/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type { UtilsResponse } from './-nav-menus-{id}-delete.schemas';

import { customInstance } from '../lib/api/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Delete navigation menu
 */
export const deleteNavMenusId = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UtilsResponse>(
    { url: `/nav-menus/${id}`, method: 'DELETE', signal },
    options
  );
};

export const getDeleteNavMenusIdMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteNavMenusId>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteNavMenusId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteNavMenusId'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteNavMenusId>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteNavMenusId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteNavMenusIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteNavMenusId>>
>;

export type DeleteNavMenusIdMutationError = unknown;

/**
 * @summary Delete navigation menu
 */
export const useDeleteNavMenusId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteNavMenusId>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteNavMenusId>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteNavMenusIdMutationOptions(options), queryClient);
};
