/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoReorderNavMenusRequest,
  UtilsResponse
} from './-nav-menus-reorder-put.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Reorder navigation menus
 */
export const putNavMenusReorder = (
    dtoReorderNavMenusRequest: DtoReorderNavMenusRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/nav-menus/reorder`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dtoReorderNavMenusRequest, signal
    },
      options);
    }



export const getPutNavMenusReorderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putNavMenusReorder>>, TError,{data: DtoReorderNavMenusRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putNavMenusReorder>>, TError,{data: DtoReorderNavMenusRequest}, TContext> => {

const mutationKey = ['putNavMenusReorder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putNavMenusReorder>>, {data: DtoReorderNavMenusRequest}> = (props) => {
          const {data} = props ?? {};

          return  putNavMenusReorder(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutNavMenusReorderMutationResult = NonNullable<Awaited<ReturnType<typeof putNavMenusReorder>>>
    export type PutNavMenusReorderMutationBody = DtoReorderNavMenusRequest
    export type PutNavMenusReorderMutationError = unknown

    /**
 * @summary Reorder navigation menus
 */
export const usePutNavMenusReorder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putNavMenusReorder>>, TError,{data: DtoReorderNavMenusRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putNavMenusReorder>>,
        TError,
        {data: DtoReorderNavMenusRequest},
        TContext
      > => {
      return useMutation(getPutNavMenusReorderMutationOptions(options), queryClient);
    }

