/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoLink {
  href?: string;
  title?: string;
}

export interface DtoColumn {
  links?: DtoLink[];
  title?: string;
}

export interface DtoFeaturedItem {
  badge?: string;
  description?: string;
  href?: string;
  image?: string;
  title?: string;
}

export interface DtoViewAll {
  href?: string;
  label?: string;
}

export interface DtoNavItemResponse {
  badge?: string;
  columns?: DtoColumn[];
  featured?: DtoFeaturedItem[];
  href?: string;
  label?: string;
  type?: string;
  viewAll?: DtoViewAll;
}

export type GetNavMenus200 = UtilsResponse & {
  data?: DtoNavItemResponse[];
};
