/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface GormDeletedAt {
  time?: string;
  /** Valid is true if Time is not NULL */
  valid?: boolean;
}

export interface ModelsProductAttribute {
  created_at?: string;
  deleted_at?: GormDeletedAt;
  id?: number;
  /**
     * @minLength 1
     * @maxLength 100
     */
  name: string;
  product_id?: number;
  updated_at?: string;
  /** @minItems 1 */
  values: string[];
}

export interface ModelsWorkflowState {
  code?: string;
  color?: string;
  created_at?: string;
  description?: string;
  id?: number;
  is_final?: boolean;
  is_initial?: boolean;
  name?: string;
  sort_order?: number;
  text_color?: string;
  updated_at?: string;
  workflow_id?: number;
}

export interface ModelsBrand {
  created_at?: string;
  description?: string;
  id?: number;
  logo_url?: string;
  name?: string;
  slug?: string;
  status?: string;
  updated_at?: string;
  workflow_state?: ModelsWorkflowState;
  workflow_state_id?: number;
}

export interface ModelsCategory {
  children?: ModelsCategory[];
  created_at?: string;
  deleted_at?: GormDeletedAt;
  description?: string;
  id?: number;
  is_active?: boolean;
  level?: number;
  /**
     * @minLength 2
     * @maxLength 100
     */
  name: string;
  /** Associations */
  parent?: ModelsCategory;
  parent_id?: number;
  path?: string;
  products?: ModelsProduct[];
  slug: string;
  updated_at?: string;
  workflow_state?: ModelsWorkflowState;
  workflow_state_id?: number;
}

export interface ModelsUser {
  created_at?: string;
  deleted_at?: GormDeletedAt;
  /** Account identity */
  email: string;
  email_verified_at?: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  first_name: string;
  /** Primary */
  id?: number;
  is_active?: boolean;
  /** Audit */
  last_login_at?: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  last_name: string;
  phone?: string;
  role?: string;
  updated_at?: string;
  workflow_state_id?: number;
}

export interface ModelsStoreReview {
  comment?: string;
  createdAt?: string;
  id?: number;
  rating?: number;
  store?: ModelsStore;
  storeID?: number;
  updatedAt?: string;
  user?: ModelsUser;
  userID?: number;
}

export interface ModelsStore {
  bannerURL?: string;
  categories?: ModelsCategory[];
  createdAt?: string;
  deletedAt?: GormDeletedAt;
  description?: string;
  followerCount?: number;
  followers?: ModelsUser[];
  id?: number;
  isVerified?: boolean;
  joinedAt?: string;
  location?: string;
  logoURL?: string;
  name?: string;
  products?: ModelsProduct[];
  rating?: number;
  returnPolicy?: string;
  reviewCount?: number;
  reviews?: ModelsStoreReview[];
  settings?: number[];
  shippingInfo?: string;
  slug?: string;
  status?: string;
  updatedAt?: string;
  /** Relationships */
  user?: ModelsUser;
  /** owner (admin user) */
  userID?: number;
}

export interface ModelsProduct {
  allow_backorder?: boolean;
  attributes?: ModelsProductAttribute[];
  barcode?: string;
  brand?: ModelsBrand;
  brand_id?: number;
  category?: ModelsCategory;
  category_id?: number;
  channels?: string[];
  colors?: string[];
  compare_at_price?: number;
  cost?: number;
  created_at?: string;
  created_by?: number;
  deleted_at?: GormDeletedAt;
  description?: string;
  id?: number;
  images?: string[];
  is_digital?: boolean;
  is_new?: boolean;
  low_stock_threshold?: number;
  meta_description?: string;
  meta_title?: string;
  /**
     * @minLength 2
     * @maxLength 255
     */
  name: string;
  price: number;
  published_at?: string;
  rating?: number;
  reviews_count?: number;
  sizes?: string[];
  sku: string;
  slug: string;
  status?: string;
  /** @minimum 0 */
  stock?: number;
  store?: ModelsStore;
  storeID?: number;
  tags?: string[];
  /** Inventory extras */
  track_inventory?: boolean;
  updated_at?: string;
  updated_by?: number;
  /** Publishing extras */
  visibility?: string;
  warehouse_location?: string;
  weight?: number;
  workflow_state?: ModelsWorkflowState;
  workflow_state_id?: number;
}

export interface ModelsOrderItem {
  created_at?: string;
  deleted_at?: GormDeletedAt;
  id?: number;
  order_id?: number;
  price?: number;
  product?: ModelsProduct;
  product_id?: number;
  quantity?: number;
  /** read-only */
  total?: number;
  updated_at?: string;
}

export interface ModelsPayment {
  amount?: number;
  created_at?: string;
  currency?: string;
  deleted_at?: GormDeletedAt;
  gateway_response?: number[];
  id?: number;
  method?: string;
  order_id?: number;
  status?: string;
  stripe_session_id?: string;
  transaction_id?: string;
  updated_at?: string;
  user_id?: number;
}

export interface ModelsShippingProviders {
  created_at?: string;
  description?: string;
  id?: number;
  is_active?: boolean;
  name?: string;
  price?: number;
  updated_at?: string;
}

export interface ModelsShipment {
  /** Shipping address */
  address_line1?: string;
  address_line2?: string;
  carrier?: string;
  city?: string;
  country?: string;
  created_at?: string;
  deleted_at?: GormDeletedAt;
  delivered_at?: string;
  estimated_delivery?: string;
  id?: number;
  order_id?: number;
  postal_code?: string;
  provider?: ModelsShippingProviders;
  provider_id?: number;
  shipped_at?: string;
  shipping_price?: number;
  state?: string;
  status?: string;
  tracking_number?: string;
  updated_at?: string;
  user_id?: number;
  workflow_state?: ModelsWorkflowState;
  workflow_state_id?: number;
}

export interface ModelsOrder {
  /** Address IDs (separate addresses table could be added later) */
  billing_address_id?: number;
  created_at?: string;
  currency?: string;
  deleted_at?: GormDeletedAt;
  id?: number;
  items?: ModelsOrderItem[];
  notes?: string;
  order_number?: string;
  payment?: ModelsPayment;
  payment_id?: number;
  shipment?: ModelsShipment;
  shipment_id?: number;
  shipping_address_id?: number;
  status?: string;
  total_amount?: number;
  updated_at?: string;
  user_id?: number;
  workflow_state_id?: number;
}

export type GetOrdersMyParams = {
/**
 * Items per page
 */
limit?: number;
/**
 * Offset (begin)
 */
offset?: number;
};

export type GetOrdersMy200Data = {
  limit?: number;
  offset?: number;
  orders?: ModelsOrder[];
  total?: number;
};

export type GetOrdersMy200 = UtilsResponse & {
  data?: GetOrdersMy200Data;
};

