/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UtilsResponse
} from './-orders-{id}-cancel-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Cancels a pending or paid order, restores stock, and refunds wallet payments.
 * @summary Cancel order
 */
export const postOrdersIdCancel = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/orders/${id}/cancel`, method: 'POST', signal
    },
      options);
    }



export const getPostOrdersIdCancelMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrdersIdCancel>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postOrdersIdCancel>>, TError,{id: number}, TContext> => {

const mutationKey = ['postOrdersIdCancel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrdersIdCancel>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postOrdersIdCancel(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostOrdersIdCancelMutationResult = NonNullable<Awaited<ReturnType<typeof postOrdersIdCancel>>>

    export type PostOrdersIdCancelMutationError = UtilsResponse

    /**
 * @summary Cancel order
 */
export const usePostOrdersIdCancel = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrdersIdCancel>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postOrdersIdCancel>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostOrdersIdCancelMutationOptions(options), queryClient);
    }

