/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoCreateProductQuestionRequest {
  /**
     * @minLength 5
     * @maxLength 1000
     */
  body: string;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoProductAnswerResponse {
  author?: string;
  body?: string;
  created_at?: string;
  id?: number;
  is_ai_reply?: boolean;
  is_store_reply?: boolean;
  question_id?: number;
}

export interface DtoProductQuestionResponse {
  answers?: DtoProductAnswerResponse[];
  author?: string;
  body?: string;
  created_at?: string;
  id?: number;
  is_owner?: boolean;
  product_id?: number;
}

export type PostProductsIdQuestions201 = UtilsResponse & {
  data?: DtoProductQuestionResponse;
};

