/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoToggleLikeRequest {
  like?: boolean;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoToggleLikeResponse {
  liked?: boolean;
}

export type PostProductsIdLike200 = UtilsResponse & {
  data?: DtoToggleLikeResponse;
};

