/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoProductAttributeResponse {
  name?: string;
  values?: string[];
}

export interface DtoBrandResponse {
  created_at?: string;
  description?: string;
  id?: number;
  logo_url?: string;
  name?: string;
  slug?: string;
  status?: string;
  updated_at?: string;
}

export interface DtoCategoryResponse {
  description?: string;
  id?: number;
  is_active?: boolean;
  level?: number;
  name?: string;
  parent_id?: number;
  path?: string;
  slug?: string;
}

export interface DtoProductWithLike {
  allow_backorder?: boolean;
  attributes?: DtoProductAttributeResponse[];
  barcode?: string;
  brand?: DtoBrandResponse;
  brand_id?: number;
  category?: DtoCategoryResponse;
  category_id?: number;
  channels?: string[];
  colors?: string[];
  compare_at_price?: number;
  cost?: number;
  created_at?: string;
  description?: string;
  id?: number;
  images?: string[];
  is_digital?: boolean;
  is_liked?: boolean;
  is_new?: boolean;
  low_stock_threshold?: number;
  meta_description?: string;
  meta_title?: string;
  name?: string;
  price?: number;
  published_at?: string;
  rating?: number;
  reviews_count?: number;
  sizes?: string[];
  sku?: string;
  slug?: string;
  status?: string;
  stock?: number;
  tags?: string[];
  track_inventory?: boolean;
  updated_at?: string;
  /** Publishing extras */
  visibility?: string;
  warehouse_location?: string;
  weight?: number;
}

export type GetProductsParams = {
  /**
   * Items per page (default 20, max 100)
   */
  limit?: number;
  /**
   * Number of items to skip
   */
  offset?: number;
  /**
   * Product status
   */
  status?: GetProductsStatus;
  /**
   * Filter by product name
   */
  name?: string;
  /**
   * Filter by SKU
   */
  sku?: string;
  /**
   * Filter by category ID
   */
  category_id?: number;
  /**
   * Filter by brand ID
   */
  brand_id?: number;
  /**
   * Minimum price
   */
  min_price?: number;
  /**
   * Maximum price
   */
  max_price?: number;
  /**
   * Minimum rating (0–5)
   */
  min_rating?: number;
  /**
   * Maximum rating
   */
  max_rating?: number;
  /**
   * Minimum review count
   */
  min_reviews?: number;
  /**
   * Maximum review count
   */
  max_reviews?: number;
  /**
   * Digital products only
   */
  is_digital?: boolean;
  /**
   * New products only
   */
  is_new?: boolean;
  /**
   * Sort order
   */
  sort?: GetProductsSort;
};

export type GetProductsStatus = (typeof GetProductsStatus)[keyof typeof GetProductsStatus];

export const GetProductsStatus = {
  active: 'active',
  draft: 'draft',
  archived: 'archived'
} as const;

export type GetProductsSort = (typeof GetProductsSort)[keyof typeof GetProductsSort];

export const GetProductsSort = {
  rating_desc: 'rating_desc',
  rating_asc: 'rating_asc',
  newest: 'newest',
  reviews_desc: 'reviews_desc',
  price_asc: 'price_asc',
  price_desc: 'price_desc'
} as const;

export type GetProducts200Data = {
  limit?: number;
  offset?: number;
  products?: DtoProductWithLike[];
  total?: number;
};

export type GetProducts200 = UtilsResponse & {
  data?: GetProducts200Data;
};
