/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoPriceHistoryPoint {
  compare_at_price?: number;
  price?: number;
  recorded_at?: string;
}

export type GetProductsIdPriceHistoryParams = {
/**
 * Number of days to include
 */
days?: number;
};

export type GetProductsIdPriceHistory200Data = {
  points?: DtoPriceHistoryPoint[];
};

export type GetProductsIdPriceHistory200 = UtilsResponse & {
  data?: GetProductsIdPriceHistory200Data;
};

