/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCreateProductAnswerRequest,
  PostProductsIdQuestionsQuestionIdAnswers201,
  UtilsResponse
} from './-products-{id}-questions-{questionId}-answers-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Post an answer; store owners are marked as store replies
 * @summary Answer a product question
 */
export const postProductsIdQuestionsQuestionIdAnswers = (
    id: string,
    questionId: number,
    dtoCreateProductAnswerRequest: DtoCreateProductAnswerRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostProductsIdQuestionsQuestionIdAnswers201>(
      {url: `/products/${id}/questions/${questionId}/answers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoCreateProductAnswerRequest, signal
    },
      options);
    }



export const getPostProductsIdQuestionsQuestionIdAnswersMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProductsIdQuestionsQuestionIdAnswers>>, TError,{id: string;questionId: number;data: DtoCreateProductAnswerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postProductsIdQuestionsQuestionIdAnswers>>, TError,{id: string;questionId: number;data: DtoCreateProductAnswerRequest}, TContext> => {

const mutationKey = ['postProductsIdQuestionsQuestionIdAnswers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProductsIdQuestionsQuestionIdAnswers>>, {id: string;questionId: number;data: DtoCreateProductAnswerRequest}> = (props) => {
          const {id,questionId,data} = props ?? {};

          return  postProductsIdQuestionsQuestionIdAnswers(id,questionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostProductsIdQuestionsQuestionIdAnswersMutationResult = NonNullable<Awaited<ReturnType<typeof postProductsIdQuestionsQuestionIdAnswers>>>
    export type PostProductsIdQuestionsQuestionIdAnswersMutationBody = DtoCreateProductAnswerRequest
    export type PostProductsIdQuestionsQuestionIdAnswersMutationError = UtilsResponse

    /**
 * @summary Answer a product question
 */
export const usePostProductsIdQuestionsQuestionIdAnswers = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProductsIdQuestionsQuestionIdAnswers>>, TError,{id: string;questionId: number;data: DtoCreateProductAnswerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postProductsIdQuestionsQuestionIdAnswers>>,
        TError,
        {id: string;questionId: number;data: DtoCreateProductAnswerRequest},
        TContext
      > => {
      return useMutation(getPostProductsIdQuestionsQuestionIdAnswersMutationOptions(options), queryClient);
    }

