/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoSuggestionsRequest,
  PostProductsSuggestions200,
  UtilsResponse
} from './-products-suggestions-post.schemas';

import { customInstance } from '../lib/api/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns products from the same categories as the provided product IDs, excluding the products themselves. Useful for cart page "you might also like".
 * @summary Get smart product suggestions
 */
export const postProductsSuggestions = (
  dtoSuggestionsRequest: DtoSuggestionsRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PostProductsSuggestions200>(
    {
      url: `/products/suggestions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: dtoSuggestionsRequest,
      signal
    },
    options
  );
};

export const getPostProductsSuggestionsMutationOptions = <
  TError = UtilsResponse,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProductsSuggestions>>,
    TError,
    { data: DtoSuggestionsRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProductsSuggestions>>,
  TError,
  { data: DtoSuggestionsRequest },
  TContext
> => {
  const mutationKey = ['postProductsSuggestions'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProductsSuggestions>>,
    { data: DtoSuggestionsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postProductsSuggestions(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostProductsSuggestionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProductsSuggestions>>
>;
export type PostProductsSuggestionsMutationBody = DtoSuggestionsRequest;
export type PostProductsSuggestionsMutationError = UtilsResponse;

/**
 * @summary Get smart product suggestions
 */
export const usePostProductsSuggestions = <TError = UtilsResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postProductsSuggestions>>,
      TError,
      { data: DtoSuggestionsRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postProductsSuggestions>>,
  TError,
  { data: DtoSuggestionsRequest },
  TContext
> => {
  return useMutation(getPostProductsSuggestionsMutationOptions(options), queryClient);
};
