/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoCreateProductAnswerRequest {
  /**
     * @minLength 2
     * @maxLength 2000
     */
  body: string;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoProductAnswerResponse {
  author?: string;
  body?: string;
  created_at?: string;
  id?: number;
  is_ai_reply?: boolean;
  is_store_reply?: boolean;
  question_id?: number;
}

export type PostProductsIdQuestionsQuestionIdAnswers201 = UtilsResponse & {
  data?: DtoProductAnswerResponse;
};

