/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DeleteProductsIdStockNotifications200,
  UtilsResponse
} from './-products-{id}-stock-notifications-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Unsubscribe from back-in-stock notifications
 */
export const deleteProductsIdStockNotifications = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DeleteProductsIdStockNotifications200>(
      {url: `/products/${id}/stock-notifications`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteProductsIdStockNotificationsMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductsIdStockNotifications>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProductsIdStockNotifications>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteProductsIdStockNotifications'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProductsIdStockNotifications>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteProductsIdStockNotifications(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductsIdStockNotificationsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProductsIdStockNotifications>>>

    export type DeleteProductsIdStockNotificationsMutationError = UtilsResponse

    /**
 * @summary Unsubscribe from back-in-stock notifications
 */
export const useDeleteProductsIdStockNotifications = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductsIdStockNotifications>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProductsIdStockNotifications>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteProductsIdStockNotificationsMutationOptions(options), queryClient);
    }

