/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoSuggestionsRequest {
  /**
     * @minimum 1
     * @maximum 20
     */
  limit?: number;
  /** @minItems 1 */
  product_ids: number[];
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoProductAttributeResponse {
  name?: string;
  values?: string[];
}

export interface DtoStateView {
  code?: string;
  color?: string;
  id?: number;
  is_final?: boolean;
  is_initial?: boolean;
  name?: string;
  sort_order?: number;
  text_color?: string;
}

export interface DtoBrandResponse {
  created_at?: string;
  description?: string;
  id?: number;
  logo_url?: string;
  name?: string;
  slug?: string;
  status?: string;
  updated_at?: string;
  workflow_state?: DtoStateView;
}

export interface DtoCategoryResponse {
  description?: string;
  id?: number;
  is_active?: boolean;
  level?: number;
  name?: string;
  parent_id?: number;
  path?: string;
  slug?: string;
}

export interface DtoProductStoreSummary {
  follower_count?: number;
  id?: number;
  is_verified?: boolean;
  location?: string;
  logo_url?: string;
  name?: string;
  rating?: number;
  return_policy?: string;
  review_count?: number;
  shipping_info?: string;
  slug?: string;
}

export interface DtoProductResponse {
  allow_backorder?: boolean;
  attributes?: DtoProductAttributeResponse[];
  barcode?: string;
  brand?: DtoBrandResponse;
  brand_id?: number;
  category?: DtoCategoryResponse;
  category_id?: number;
  channels?: string[];
  colors?: string[];
  compare_at_price?: number;
  cost?: number;
  created_at?: string;
  description?: string;
  id?: number;
  images?: string[];
  is_digital?: boolean;
  is_new?: boolean;
  low_stock_threshold?: number;
  meta_description?: string;
  meta_title?: string;
  name?: string;
  price?: number;
  published_at?: string;
  rating?: number;
  reviews_count?: number;
  sizes?: string[];
  sku?: string;
  slug?: string;
  status?: string;
  stock?: number;
  store?: DtoProductStoreSummary;
  store_id?: number;
  tags?: string[];
  track_inventory?: boolean;
  updated_at?: string;
  /** Publishing extras */
  visibility?: string;
  warehouse_location?: string;
  weight?: number;
  workflow_state?: DtoStateView;
}

export type PostProductsSuggestions200 = UtilsResponse & {
  data?: DtoProductResponse[];
};

