/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export type PutProfileBody = { [key: string]: unknown };

export type PutProfile200Data = {
  email?: string;
  first_name?: string;
  id?: number;
  last_name?: string;
  phone?: string;
};

export type PutProfile200 = UtilsResponse & {
  data?: PutProfile200Data;
};
