/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPushVapidPublicKey200
} from './-push-vapid-public-key-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the public VAPID key used by the browser PushManager.subscribe()
 * @summary Get VAPID public key
 */
export const getPushVapidPublicKey = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetPushVapidPublicKey200>(
      {url: `/push/vapid-public-key`, method: 'GET', signal
    },
      options);
    }




export const getGetPushVapidPublicKeyQueryKey = () => {
    return [
    `/push/vapid-public-key`
    ] as const;
    }


export const getGetPushVapidPublicKeyQueryOptions = <TData = Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPushVapidPublicKeyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPushVapidPublicKey>>> = ({ signal }) => getPushVapidPublicKey(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPushVapidPublicKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getPushVapidPublicKey>>>
export type GetPushVapidPublicKeyQueryError = unknown


export function useGetPushVapidPublicKey<TData = Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPushVapidPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getPushVapidPublicKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPushVapidPublicKey<TData = Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPushVapidPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getPushVapidPublicKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPushVapidPublicKey<TData = Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get VAPID public key
 */

export function useGetPushVapidPublicKey<TData = Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPushVapidPublicKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPushVapidPublicKeyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







