/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCreateReturnRequest,
  PostReturns201
} from './-returns-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create return request
 */
export const postReturns = (
    dtoCreateReturnRequest: DtoCreateReturnRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostReturns201>(
      {url: `/returns`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoCreateReturnRequest, signal
    },
      options);
    }



export const getPostReturnsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReturns>>, TError,{data: DtoCreateReturnRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postReturns>>, TError,{data: DtoCreateReturnRequest}, TContext> => {

const mutationKey = ['postReturns'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReturns>>, {data: DtoCreateReturnRequest}> = (props) => {
          const {data} = props ?? {};

          return  postReturns(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReturnsMutationResult = NonNullable<Awaited<ReturnType<typeof postReturns>>>
    export type PostReturnsMutationBody = DtoCreateReturnRequest
    export type PostReturnsMutationError = unknown

    /**
 * @summary Create return request
 */
export const usePostReturns = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReturns>>, TError,{data: DtoCreateReturnRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReturns>>,
        TError,
        {data: DtoCreateReturnRequest},
        TContext
      > => {
      return useMutation(getPostReturnsMutationOptions(options), queryClient);
    }

