/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetReturnsMyParams,
  UtilsResponse
} from './-returns-my-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List my returns
 */
export const getReturnsMy = (
    params?: GetReturnsMyParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/returns/my`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetReturnsMyQueryKey = (params?: GetReturnsMyParams,) => {
    return [
    `/returns/my`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetReturnsMyQueryOptions = <TData = Awaited<ReturnType<typeof getReturnsMy>>, TError = unknown>(params?: GetReturnsMyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReturnsMy>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReturnsMyQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReturnsMy>>> = ({ signal }) => getReturnsMy(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReturnsMy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReturnsMyQueryResult = NonNullable<Awaited<ReturnType<typeof getReturnsMy>>>
export type GetReturnsMyQueryError = unknown


export function useGetReturnsMy<TData = Awaited<ReturnType<typeof getReturnsMy>>, TError = unknown>(
 params: undefined |  GetReturnsMyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReturnsMy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReturnsMy>>,
          TError,
          Awaited<ReturnType<typeof getReturnsMy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReturnsMy<TData = Awaited<ReturnType<typeof getReturnsMy>>, TError = unknown>(
 params?: GetReturnsMyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReturnsMy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReturnsMy>>,
          TError,
          Awaited<ReturnType<typeof getReturnsMy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReturnsMy<TData = Awaited<ReturnType<typeof getReturnsMy>>, TError = unknown>(
 params?: GetReturnsMyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReturnsMy>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my returns
 */

export function useGetReturnsMy<TData = Awaited<ReturnType<typeof getReturnsMy>>, TError = unknown>(
 params?: GetReturnsMyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReturnsMy>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReturnsMyQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







