/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoCreateReviewRequest {
  comment?: string;
  product_id: number;
  /**
     * @minimum 1
     * @maximum 5
     */
  rating: number;
  title?: string;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface GormDeletedAt {
  time?: string;
  /** Valid is true if Time is not NULL */
  valid?: boolean;
}

export interface ModelsReview {
  comment?: string;
  created_at?: string;
  deleted_at?: GormDeletedAt;
  id?: number;
  is_verified?: boolean;
  product_id?: number;
  /**
     * @minimum 1
     * @maximum 5
     */
  rating?: number;
  title?: string;
  updated_at?: string;
  user_id?: number;
}

export type PostReviews201 = UtilsResponse & {
  data?: ModelsReview;
};

