/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoCategoryResponse {
  description?: string;
  id?: number;
  is_active?: boolean;
  level?: number;
  name?: string;
  parent_id?: number;
  path?: string;
  slug?: string;
}

export interface DtoProductAttributeResponse {
  name?: string;
  values?: string[];
}

export interface DtoBrandResponse {
  created_at?: string;
  description?: string;
  id?: number;
  logo_url?: string;
  name?: string;
  slug?: string;
  status?: string;
  updated_at?: string;
}

export interface DtoProductResponse {
  allow_backorder?: boolean;
  attributes?: DtoProductAttributeResponse[];
  barcode?: string;
  brand?: DtoBrandResponse;
  brand_id?: number;
  category?: DtoCategoryResponse;
  category_id?: number;
  channels?: string[];
  colors?: string[];
  compare_at_price?: number;
  cost?: number;
  created_at?: string;
  description?: string;
  id?: number;
  images?: string[];
  is_digital?: boolean;
  is_new?: boolean;
  low_stock_threshold?: number;
  meta_description?: string;
  meta_title?: string;
  name?: string;
  price?: number;
  published_at?: string;
  rating?: number;
  reviews_count?: number;
  sizes?: string[];
  sku?: string;
  slug?: string;
  status?: string;
  stock?: number;
  tags?: string[];
  track_inventory?: boolean;
  updated_at?: string;
  /** Publishing extras */
  visibility?: string;
  warehouse_location?: string;
  weight?: number;
}

export interface DtoStoreResponse {
  banner_url?: string;
  categories?: DtoCategoryResponse[];
  description?: string;
  follower_count?: number;
  id?: number;
  is_followed?: boolean;
  is_verified?: boolean;
  joined_at?: string;
  location?: string;
  logo_url?: string;
  name?: string;
  rating?: number;
  return_policy?: string;
  review_count?: number;
  shipping_info?: string;
  slug?: string;
}

export interface DtoSearchResponse {
  categories?: DtoCategoryResponse[];
  products?: DtoProductResponse[];
  stores?: DtoStoreResponse[];
  total?: number;
}

export type GetSearchParams = {
  /**
   * Search query (optional for filter-only browse)
   */
  q?: string;
  /**
   * Items per page (default 10, max 50)
   */
  limit?: number;
  /**
   * Offset for pagination
   */
  offset?: number;
  /**
   * Filter by category ID
   */
  category_id?: number;
  /**
   * Filter by category slug
   */
  category_slug?: string;
  /**
   * Filter by store ID
   */
  store_id?: number;
  /**
   * Minimum price
   */
  min_price?: number;
  /**
   * Maximum price
   */
  max_price?: number;
  /**
   * Minimum rating
   */
  min_rating?: number;
  /**
   * Digital products only
   */
  is_digital?: boolean;
  /**
   * New arrivals only
   */
  is_new?: boolean;
  /**
   * In-stock products only
   */
  in_stock?: boolean;
  /**
   * On-sale products only
   */
  on_sale?: boolean;
  /**
   * Sort order (price_asc,price_desc,rating_desc,newest,popular)
   */
  sort?: string;
};

export type GetSearch200 = UtilsResponse & {
  data?: DtoSearchResponse;
};
