/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoSuggestionItem {
  id?: number;
  image?: string;
  name?: string;
  price?: number;
  slug?: string;
  type?: string;
}

export interface DtoSuggestionsResponse {
  suggestions?: DtoSuggestionItem[];
}

export type GetSearchSuggestionsParams = {
/**
 * Partial query
 */
q: string;
/**
 * Max suggestions (default 8, max 20)
 */
limit?: number;
};

export type GetSearchSuggestions200 = UtilsResponse & {
  data?: DtoSuggestionsResponse;
};

