/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSettingsKey200,
  UtilsResponse
} from './-settings-{key}-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the value (any JSON) for the given setting key.
 * @summary Get a setting by key
 */
export const getSettingsKey = (
    key: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetSettingsKey200>(
      {url: `/settings/${key}`, method: 'GET', signal
    },
      options);
    }




export const getGetSettingsKeyQueryKey = (key: string,) => {
    return [
    `/settings/${key}`
    ] as const;
    }


export const getGetSettingsKeyQueryOptions = <TData = Awaited<ReturnType<typeof getSettingsKey>>, TError = UtilsResponse>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsKeyQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettingsKey>>> = ({ signal }) => getSettingsKey(key, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(key), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettingsKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSettingsKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getSettingsKey>>>
export type GetSettingsKeyQueryError = UtilsResponse


export function useGetSettingsKey<TData = Awaited<ReturnType<typeof getSettingsKey>>, TError = UtilsResponse>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettingsKey>>,
          TError,
          Awaited<ReturnType<typeof getSettingsKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettingsKey<TData = Awaited<ReturnType<typeof getSettingsKey>>, TError = UtilsResponse>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettingsKey>>,
          TError,
          Awaited<ReturnType<typeof getSettingsKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettingsKey<TData = Awaited<ReturnType<typeof getSettingsKey>>, TError = UtilsResponse>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a setting by key
 */

export function useGetSettingsKey<TData = Awaited<ReturnType<typeof getSettingsKey>>, TError = UtilsResponse>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingsKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSettingsKeyQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







