/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UtilsResponse
} from './-settings-{key}-delete.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Deletes a setting by its key. Admin only.
 * @summary Delete a setting
 */
export const deleteSettingsKey = (
    key: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/settings/${key}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteSettingsKeyMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSettingsKey>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSettingsKey>>, TError,{key: string}, TContext> => {

const mutationKey = ['deleteSettingsKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSettingsKey>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  deleteSettingsKey(key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSettingsKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSettingsKey>>>

    export type DeleteSettingsKeyMutationError = UtilsResponse

    /**
 * @summary Delete a setting
 */
export const useDeleteSettingsKey = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSettingsKey>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSettingsKey>>,
        TError,
        {key: string},
        TContext
      > => {
      return useMutation(getDeleteSettingsKeyMutationOptions(options), queryClient);
    }

