/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetShipmentsIdAvailableTransitions200
} from './-shipments-{id}-available-transitions-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List shipment workflow transitions (admin)
 */
export const getShipmentsIdAvailableTransitions = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetShipmentsIdAvailableTransitions200>(
      {url: `/shipments/${id}/available-transitions`, method: 'GET', signal
    },
      options);
    }




export const getGetShipmentsIdAvailableTransitionsQueryKey = (id: number,) => {
    return [
    `/shipments/${id}/available-transitions`
    ] as const;
    }


export const getGetShipmentsIdAvailableTransitionsQueryOptions = <TData = Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShipmentsIdAvailableTransitionsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>> = ({ signal }) => getShipmentsIdAvailableTransitions(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetShipmentsIdAvailableTransitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>>
export type GetShipmentsIdAvailableTransitionsQueryError = unknown


export function useGetShipmentsIdAvailableTransitions<TData = Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>,
          TError,
          Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShipmentsIdAvailableTransitions<TData = Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>,
          TError,
          Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShipmentsIdAvailableTransitions<TData = Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List shipment workflow transitions (admin)
 */

export function useGetShipmentsIdAvailableTransitions<TData = Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsIdAvailableTransitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetShipmentsIdAvailableTransitionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







