/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetShipmentsId200,
  UtilsResponse
} from './-shipments-{id}-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a shipment. Admin can see any; users see only shipments belonging to their orders.
 * @summary Get shipment by ID
 */
export const getShipmentsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetShipmentsId200>(
      {url: `/shipments/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetShipmentsIdQueryKey = (id: number,) => {
    return [
    `/shipments/${id}`
    ] as const;
    }


export const getGetShipmentsIdQueryOptions = <TData = Awaited<ReturnType<typeof getShipmentsId>>, TError = UtilsResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShipmentsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShipmentsId>>> = ({ signal }) => getShipmentsId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShipmentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetShipmentsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getShipmentsId>>>
export type GetShipmentsIdQueryError = UtilsResponse


export function useGetShipmentsId<TData = Awaited<ReturnType<typeof getShipmentsId>>, TError = UtilsResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShipmentsId>>,
          TError,
          Awaited<ReturnType<typeof getShipmentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShipmentsId<TData = Awaited<ReturnType<typeof getShipmentsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShipmentsId>>,
          TError,
          Awaited<ReturnType<typeof getShipmentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShipmentsId<TData = Awaited<ReturnType<typeof getShipmentsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get shipment by ID
 */

export function useGetShipmentsId<TData = Awaited<ReturnType<typeof getShipmentsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShipmentsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetShipmentsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







