/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoCreateShippingProviderRequest {
  description?: string;
  is_active?: boolean;
  name: string;
  /** @minimum 0 */
  price?: number;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface ModelsShippingProviders {
  created_at?: string;
  description?: string;
  id?: number;
  is_active?: boolean;
  name?: string;
  price?: number;
  updated_at?: string;
}

export type PostShippingProviders201 = UtilsResponse & {
  data?: ModelsShippingProviders;
};

