/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type { GetStores200, GetStoresParams, UtilsResponse } from './-stores-get.schemas';

import { customInstance } from '../lib/api/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get stores with pagination, search, location, rating, category filters
 * @summary List stores
 */
export const getStores = (
  params?: GetStoresParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<GetStores200>({ url: `/stores`, method: 'GET', params, signal }, options);
};

export const getGetStoresQueryKey = (params?: GetStoresParams) => {
  return [`/stores`, ...(params ? [params] : [])] as const;
};

export const getGetStoresQueryOptions = <
  TData = Awaited<ReturnType<typeof getStores>>,
  TError = UtilsResponse
>(
  params?: GetStoresParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStoresQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStores>>> = ({ signal }) =>
    getStores(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStores>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStoresQueryResult = NonNullable<Awaited<ReturnType<typeof getStores>>>;
export type GetStoresQueryError = UtilsResponse;

export function useGetStores<TData = Awaited<ReturnType<typeof getStores>>, TError = UtilsResponse>(
  params: undefined | GetStoresParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStores>>,
          TError,
          Awaited<ReturnType<typeof getStores>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetStores<TData = Awaited<ReturnType<typeof getStores>>, TError = UtilsResponse>(
  params?: GetStoresParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStores>>,
          TError,
          Awaited<ReturnType<typeof getStores>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetStores<TData = Awaited<ReturnType<typeof getStores>>, TError = UtilsResponse>(
  params?: GetStoresParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List stores
 */

export function useGetStores<TData = Awaited<ReturnType<typeof getStores>>, TError = UtilsResponse>(
  params?: GetStoresParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetStoresQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
