/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCreateStoreReviewRequest,
  UtilsResponse
} from './-stores-{slug}-reviews-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Leave a rating and comment for a store
 * @summary Create store review
 */
export const postStoresSlugReviews = (
    slug: string,
    dtoCreateStoreReviewRequest: DtoCreateStoreReviewRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/stores/${slug}/reviews`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoCreateStoreReviewRequest, signal
    },
      options);
    }



export const getPostStoresSlugReviewsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStoresSlugReviews>>, TError,{slug: string;data: DtoCreateStoreReviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postStoresSlugReviews>>, TError,{slug: string;data: DtoCreateStoreReviewRequest}, TContext> => {

const mutationKey = ['postStoresSlugReviews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postStoresSlugReviews>>, {slug: string;data: DtoCreateStoreReviewRequest}> = (props) => {
          const {slug,data} = props ?? {};

          return  postStoresSlugReviews(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostStoresSlugReviewsMutationResult = NonNullable<Awaited<ReturnType<typeof postStoresSlugReviews>>>
    export type PostStoresSlugReviewsMutationBody = DtoCreateStoreReviewRequest
    export type PostStoresSlugReviewsMutationError = unknown

    /**
 * @summary Create store review
 */
export const usePostStoresSlugReviews = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStoresSlugReviews>>, TError,{slug: string;data: DtoCreateStoreReviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postStoresSlugReviews>>,
        TError,
        {slug: string;data: DtoCreateStoreReviewRequest},
        TContext
      > => {
      return useMutation(getPostStoresSlugReviewsMutationOptions(options), queryClient);
    }

