/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoPresignUploadRequest,
  PostUploadsPresign200,
  UtilsResponse
} from './-uploads-presign-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a short-lived PUT URL; client uploads file bytes to upload_url with Content-Type header.
 * @summary Presign upload
 */
export const postUploadsPresign = (
    dtoPresignUploadRequest: DtoPresignUploadRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostUploadsPresign200>(
      {url: `/uploads/presign`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoPresignUploadRequest, signal
    },
      options);
    }



export const getPostUploadsPresignMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUploadsPresign>>, TError,{data: DtoPresignUploadRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUploadsPresign>>, TError,{data: DtoPresignUploadRequest}, TContext> => {

const mutationKey = ['postUploadsPresign'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUploadsPresign>>, {data: DtoPresignUploadRequest}> = (props) => {
          const {data} = props ?? {};

          return  postUploadsPresign(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUploadsPresignMutationResult = NonNullable<Awaited<ReturnType<typeof postUploadsPresign>>>
    export type PostUploadsPresignMutationBody = DtoPresignUploadRequest
    export type PostUploadsPresignMutationError = UtilsResponse

    /**
 * @summary Presign upload
 */
export const usePostUploadsPresign = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUploadsPresign>>, TError,{data: DtoPresignUploadRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUploadsPresign>>,
        TError,
        {data: DtoPresignUploadRequest},
        TContext
      > => {
      return useMutation(getPostUploadsPresignMutationOptions(options), queryClient);
    }

