/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export type DtoPresignUploadRequestPurpose = typeof DtoPresignUploadRequestPurpose[keyof typeof DtoPresignUploadRequestPurpose];


export const DtoPresignUploadRequestPurpose = {
  product: 'product',
  avatar: 'avatar',
  store: 'store',
  brand: 'brand',
  media: 'media',
} as const;

export interface DtoPresignUploadRequest {
  /** @maxLength 128 */
  content_type: string;
  /** @maxLength 255 */
  filename: string;
  purpose: DtoPresignUploadRequestPurpose;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoPresignUploadResponse {
  expires_at?: string;
  key?: string;
  method?: string;
  public_url?: string;
  upload_url?: string;
}

export type PostUploadsPresign200 = UtilsResponse & {
  data?: DtoPresignUploadResponse;
};

