/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export interface DtoUploadConfigResponse {
  enabled?: boolean;
  max_size_mb?: number;
  presign_ttl_seconds?: number;
}

export type GetUploadsConfig200 = UtilsResponse & {
  data?: DtoUploadConfigResponse;
};

