/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export type GetUsersParams = {
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Offset (skip number of items)
 * @minimum 0
 */
offset?: number;
/**
 * Filter by active status
 */
is_active?: boolean;
/**
 * Partial match on email
 */
email?: string;
/**
 * Partial match on phone
 */
phone?: string;
/**
 * Partial match on first name
 */
first_name?: string;
/**
 * Partial match on last name
 */
last_name?: string;
/**
 * Exact match on role
 */
role?: GetUsersRole;
};

export type GetUsersRole = typeof GetUsersRole[keyof typeof GetUsersRole];


export const GetUsersRole = {
  user: 'user',
  admin: 'admin',
  moderator: 'moderator',
} as const;

export type GetUsers200DataUsersItem = {
  created_at?: string;
  email?: string;
  first_name?: string;
  id?: number;
  is_active?: boolean;
  last_name?: string;
  phone?: string;
  role?: string;
};

export type GetUsers200Data = {
  limit?: number;
  offset?: number;
  total?: number;
  users?: GetUsers200DataUsersItem[];
};

export type GetUsers200 = UtilsResponse & {
  data?: GetUsers200Data;
};

