/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetVendorStores200,
  UtilsResponse
} from './-vendor-stores-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns stores owned by the current seller, or all stores for admins/moderators
 * @summary List vendor stores
 */
export const getVendorStores = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetVendorStores200>(
      {url: `/vendor/stores`, method: 'GET', signal
    },
      options);
    }




export const getGetVendorStoresQueryKey = () => {
    return [
    `/vendor/stores`
    ] as const;
    }


export const getGetVendorStoresQueryOptions = <TData = Awaited<ReturnType<typeof getVendorStores>>, TError = UtilsResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVendorStores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVendorStoresQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVendorStores>>> = ({ signal }) => getVendorStores(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVendorStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVendorStoresQueryResult = NonNullable<Awaited<ReturnType<typeof getVendorStores>>>
export type GetVendorStoresQueryError = UtilsResponse


export function useGetVendorStores<TData = Awaited<ReturnType<typeof getVendorStores>>, TError = UtilsResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVendorStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVendorStores>>,
          TError,
          Awaited<ReturnType<typeof getVendorStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVendorStores<TData = Awaited<ReturnType<typeof getVendorStores>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVendorStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVendorStores>>,
          TError,
          Awaited<ReturnType<typeof getVendorStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVendorStores<TData = Awaited<ReturnType<typeof getVendorStores>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVendorStores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List vendor stores
 */

export function useGetVendorStores<TData = Awaited<ReturnType<typeof getVendorStores>>, TError = UtilsResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVendorStores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVendorStoresQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







