/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetWalletTransactionsId200,
  UtilsResponse
} from './-wallet-transactions-{id}-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Fetch details of a specific wallet transaction.
 * @summary Get transaction details
 */
export const getWalletTransactionsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetWalletTransactionsId200>(
      {url: `/wallet/transactions/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetWalletTransactionsIdQueryKey = (id: number,) => {
    return [
    `/wallet/transactions/${id}`
    ] as const;
    }


export const getGetWalletTransactionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getWalletTransactionsId>>, TError = UtilsResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletTransactionsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletTransactionsId>>> = ({ signal }) => getWalletTransactionsId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWalletTransactionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletTransactionsId>>>
export type GetWalletTransactionsIdQueryError = UtilsResponse


export function useGetWalletTransactionsId<TData = Awaited<ReturnType<typeof getWalletTransactionsId>>, TError = UtilsResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletTransactionsId>>,
          TError,
          Awaited<ReturnType<typeof getWalletTransactionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWalletTransactionsId<TData = Awaited<ReturnType<typeof getWalletTransactionsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletTransactionsId>>,
          TError,
          Awaited<ReturnType<typeof getWalletTransactionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWalletTransactionsId<TData = Awaited<ReturnType<typeof getWalletTransactionsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get transaction details
 */

export function useGetWalletTransactionsId<TData = Awaited<ReturnType<typeof getWalletTransactionsId>>, TError = UtilsResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWalletTransactionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







