/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
export interface DtoDepositRequest {
  amount: number;
  /** for future gateway integration */
  payment_method?: string;
}

export interface UtilsResponse {
  code?: number;
  error?: string;
  message?: string;
  success?: boolean;
}

export type PostWalletDeposit200Data = {
  transaction_id?: number;
};

export type PostWalletDeposit200 = UtilsResponse & {
  data?: PostWalletDeposit200Data;
};
