/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoPerformTransitionRequest,
  PostWorkflowsKeyEntityIdTransition200,
  UtilsResponse
} from './-workflows-{key}-{entityId}-transition-post.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Moves an entity to a new state by firing an event. Records who changed what, when.
 * @summary Perform a workflow transition
 */
export const postWorkflowsKeyEntityIdTransition = (
    key: string,
    entityId: number,
    dtoPerformTransitionRequest: DtoPerformTransitionRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostWorkflowsKeyEntityIdTransition200>(
      {url: `/workflows/${key}/${entityId}/transition`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoPerformTransitionRequest, signal
    },
      options);
    }



export const getPostWorkflowsKeyEntityIdTransitionMutationOptions = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkflowsKeyEntityIdTransition>>, TError,{key: string;entityId: number;data: DtoPerformTransitionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkflowsKeyEntityIdTransition>>, TError,{key: string;entityId: number;data: DtoPerformTransitionRequest}, TContext> => {

const mutationKey = ['postWorkflowsKeyEntityIdTransition'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkflowsKeyEntityIdTransition>>, {key: string;entityId: number;data: DtoPerformTransitionRequest}> = (props) => {
          const {key,entityId,data} = props ?? {};

          return  postWorkflowsKeyEntityIdTransition(key,entityId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostWorkflowsKeyEntityIdTransitionMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkflowsKeyEntityIdTransition>>>
    export type PostWorkflowsKeyEntityIdTransitionMutationBody = DtoPerformTransitionRequest
    export type PostWorkflowsKeyEntityIdTransitionMutationError = UtilsResponse

    /**
 * @summary Perform a workflow transition
 */
export const usePostWorkflowsKeyEntityIdTransition = <TError = UtilsResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkflowsKeyEntityIdTransition>>, TError,{key: string;entityId: number;data: DtoPerformTransitionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkflowsKeyEntityIdTransition>>,
        TError,
        {key: string;entityId: number;data: DtoPerformTransitionRequest},
        TContext
      > => {
      return useMutation(getPostWorkflowsKeyEntityIdTransitionMutationOptions(options), queryClient);
    }

