/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetWorkflowsKey200,
  UtilsResponse
} from './-workflows-{key}-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a workflow with its states (including color codes) and transitions.
 * @summary Get workflow definition
 */
export const getWorkflowsKey = (
    key: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetWorkflowsKey200>(
      {url: `/workflows/${key}`, method: 'GET', signal
    },
      options);
    }




export const getGetWorkflowsKeyQueryKey = (key: string,) => {
    return [
    `/workflows/${key}`
    ] as const;
    }


export const getGetWorkflowsKeyQueryOptions = <TData = Awaited<ReturnType<typeof getWorkflowsKey>>, TError = UtilsResponse>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkflowsKeyQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkflowsKey>>> = ({ signal }) => getWorkflowsKey(key, requestOptions, signal);





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkflowsKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkflowsKey>>>
export type GetWorkflowsKeyQueryError = UtilsResponse


export function useGetWorkflowsKey<TData = Awaited<ReturnType<typeof getWorkflowsKey>>, TError = UtilsResponse>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkflowsKey>>,
          TError,
          Awaited<ReturnType<typeof getWorkflowsKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkflowsKey<TData = Awaited<ReturnType<typeof getWorkflowsKey>>, TError = UtilsResponse>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkflowsKey>>,
          TError,
          Awaited<ReturnType<typeof getWorkflowsKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkflowsKey<TData = Awaited<ReturnType<typeof getWorkflowsKey>>, TError = UtilsResponse>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get workflow definition
 */

export function useGetWorkflowsKey<TData = Awaited<ReturnType<typeof getWorkflowsKey>>, TError = UtilsResponse>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkflowsKeyQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







