/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetWorkflowsKeyEntityIdHistoryParams,
  UtilsResponse
} from './-workflows-{key}-{entityId}-history-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns who changed the entity's state, from/to (with colors), when, and any note.
 * @summary Get workflow history
 */
export const getWorkflowsKeyEntityIdHistory = (
    key: string,
    entityId: number,
    params?: GetWorkflowsKeyEntityIdHistoryParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UtilsResponse>(
      {url: `/workflows/${key}/${entityId}/history`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetWorkflowsKeyEntityIdHistoryQueryKey = (key: string,
    entityId: number,
    params?: GetWorkflowsKeyEntityIdHistoryParams,) => {
    return [
    `/workflows/${key}/${entityId}/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetWorkflowsKeyEntityIdHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError = unknown>(key: string,
    entityId: number,
    params?: GetWorkflowsKeyEntityIdHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkflowsKeyEntityIdHistoryQueryKey(key,entityId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>> = ({ signal }) => getWorkflowsKeyEntityIdHistory(key,entityId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined && entityId !== null && entityId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkflowsKeyEntityIdHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>>
export type GetWorkflowsKeyEntityIdHistoryQueryError = unknown


export function useGetWorkflowsKeyEntityIdHistory<TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError = unknown>(
 key: string,
    entityId: number,
    params: undefined |  GetWorkflowsKeyEntityIdHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>,
          TError,
          Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkflowsKeyEntityIdHistory<TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError = unknown>(
 key: string,
    entityId: number,
    params?: GetWorkflowsKeyEntityIdHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>,
          TError,
          Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkflowsKeyEntityIdHistory<TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError = unknown>(
 key: string,
    entityId: number,
    params?: GetWorkflowsKeyEntityIdHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get workflow history
 */

export function useGetWorkflowsKeyEntityIdHistory<TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError = unknown>(
 key: string,
    entityId: number,
    params?: GetWorkflowsKeyEntityIdHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkflowsKeyEntityIdHistoryQueryOptions(key,entityId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







