/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Shopping Platform API
 * Production-grade e-commerce backend
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetWorkflowsKeyEntityIdAvailableTransitions200
} from './-workflows-{key}-{entityId}-available-transitions-get.schemas';

import { customInstance } from '../lib/api/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List available transitions
 */
export const getWorkflowsKeyEntityIdAvailableTransitions = (
    key: string,
    entityId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetWorkflowsKeyEntityIdAvailableTransitions200>(
      {url: `/workflows/${key}/${entityId}/available-transitions`, method: 'GET', signal
    },
      options);
    }




export const getGetWorkflowsKeyEntityIdAvailableTransitionsQueryKey = (key: string,
    entityId: number,) => {
    return [
    `/workflows/${key}/${entityId}/available-transitions`
    ] as const;
    }


export const getGetWorkflowsKeyEntityIdAvailableTransitionsQueryOptions = <TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError = unknown>(key: string,
    entityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkflowsKeyEntityIdAvailableTransitionsQueryKey(key,entityId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>> = ({ signal }) => getWorkflowsKeyEntityIdAvailableTransitions(key,entityId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined && entityId !== null && entityId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkflowsKeyEntityIdAvailableTransitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>>
export type GetWorkflowsKeyEntityIdAvailableTransitionsQueryError = unknown


export function useGetWorkflowsKeyEntityIdAvailableTransitions<TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError = unknown>(
 key: string,
    entityId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>,
          TError,
          Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkflowsKeyEntityIdAvailableTransitions<TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError = unknown>(
 key: string,
    entityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>,
          TError,
          Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkflowsKeyEntityIdAvailableTransitions<TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError = unknown>(
 key: string,
    entityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List available transitions
 */

export function useGetWorkflowsKeyEntityIdAvailableTransitions<TData = Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError = unknown>(
 key: string,
    entityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkflowsKeyEntityIdAvailableTransitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkflowsKeyEntityIdAvailableTransitionsQueryOptions(key,entityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







